from .data_types import Culture
import copy

#List of Cultures
test_roman = Culture('roman',
                    ['Maximus','Gaius','Quintus','Canis'],
                    ['dynn_Nepos','dynn_Iulius','dynn_Augustus','dynn_Robertus'],
                    father_name_chance = 0.35,
                    grandfather_name_chance = 0.35)
sami = Culture('sami',
               ["A_ggi","A_igesA_rri","A_ilu","A_mmot","A_ra","A_rrajuoksa","A_sllat","E_oavvA_","Ahkemiella",
                "Algebaeivi","Baeivi","Baeivvet","Biejan","BijA_s","Bilzi","DA_vgon","DuttA_","GA_ivvas",
                "GA_ktu","Henes","JA_rre","Jeansa","Juvven","LA_gon","LA_vrrohas","LeammA_","Mellet","Mihka","Mohkku",
                "Mokci","NA_hkol","NA_innas","Njulgu","OavA_n","Orddot","RA_stos","Riibma","Ruigi","SA_rra",
                "Speaidna","Viggu"],
               ["dynn_Ahkebeaivi","dynn_Ahkemiella","dynn_GA_ivvaS_","dynn_Varakid","dynn_Sarakid","dynn_Hasabid",\
                "dynn_Tatvid","dynn_Yurakid","dynn_Jio","dynn_Simo","dynn_Kuni","dynn_Rahna","dynn_Sochioch",\
                "dynn_Jochmoch","dynn_Avioware","dynn_Enare","dynn_Enaraby","dynn_Kimi","dynn_Suenekelle",\
                "dynn_Warager","dynn_Teno","dynn_Maggeroe","dynn_Kittilaby","dynn_Sambeaoby","dynn_Pajersvi",\
                "dynn_Kielit","dynn_Kemeloe"],
               father_name_chance = 0.0,
               grandfather_name_chance = 0.0,
              )
komi = Culture('komi',
              ["Andyamo","Arnaz","Arti","Artis","Arvo","Aymort","Azeg","Biur","Biyar","Burmort","Chichayka","Chuga",
               "Dergun","Deryab","Dobrinya","Dokya","Dondy","Gazheg","Hulyen","Inzhay","Irter","Lyneg","Lysko",
               "Kezhapa","Kezhay","Kezhedey","Kezhevat","Kichay","Koksha","Kuaz","Kudym-Osh","Kya","Kyldysin",
               "Malyaka","Malyy","Meltsayka","Mosheg","Nalka","Nuyaksha","Nuyanza","Nuyat","Nydog","Nylog","Odeg",
               "Onika","Osh","Oshmar","Oshypel","Ovtay","Ozheg","Ozhmeg","Pakstyan","Paksyay","Paksyut","Parush",
               "Pivtsay","Pokshayka","Putyayka","Pyera","Rateg","Rayda","Sarin","Sektev","Setyamka","Shindyay",
               "Shypicha","Shyrpuzh","Spira","Syrka","Tikshayka","Tuhan","Tyueykezhut","Tyutyuk","Tugan","Turush",
               "Uchva","Varaka","Vechkas","Velmayka","Virdyan","Viryas","Viryay","Vokan","Yirkap","Ylvan","Zarny",
               "Zhebeg","Zhuneg","Zyryan"],
              ["dynn_Syktyvkar","dynn_Permyakid","dynn_Azegid","dynn_Gachegid","dynn_Zhebegid","dynn_Lunegid",
               "dynn_Zhunegid","dynn_Irtegid","dynn_Moshegid","dynn_Nydogid","dynn_Nylogid","dynn_Ozhegid",
               "dynn_Odegid","dynn_Rategid","dynn_Permyakid"],
              father_name_chance = 0.0,
              grandfather_name_chance = 0.0,
              )
fenni = Culture('fenni',
               ["Aarto","Aatos","Aatso","Agafana","Ahma","Ahvo","Aimo","Akkila","Alestari","Antippa","Arhippa","Armas",
               "Arssi","Arttju","Arvo","Asikko","Asko","Borissa","Buklei","Djemi","Ensio","Erkki","Everkki","Fadei",
               "Fedotta","Fedula","Filatkie","Grigo","Haapa","Hannu","Harle","Havu","Henri","Hermo","Heroi","Hilippa",
               "Hilppa","Hintsa","Homa","Hotti","Huohvana","Ignoi","Ihanti","Into","Ipatti","Iroda","Jaakoppi","Jalo",
               "Jehki","Jelisei","Jemi","Jestoi","Jeuloi","Jeygi","Jeyssi","Johora","Jurva","Jyrki","Kaarle","Kaleva",
               "Kalevi","Karppa","Kassu","Kauro","Kettu","Kibroi","KirilA_","Kolli","Kondro","Konoi","Kormi","Kostja",
               "Kuisma","Kuuti","KyyrO_","Lalli","Lari","Lauri","Lemetti","Levoi","Luka","Makko","Maksima","Manu",
               "Martiska","Matti","Mielitty","Miemo","Miikkula","Miina","Miitrei","MikittA_","Mikko","Mirona","Mitfora",
               "Moissi","Mokki","Naasarei","Niikko","Ofonja","Oiva","Olavi","Onni","Ontto","Onu","Otso","PA_iviO_",
               "PA_ntti","Paavo","Pamfila","Pankko","Pankraatei","Pantelei","Parmoi","Pekko","Pentti","PiminA_","Pirdoi",
               "Poavila","Porfi","Potoi","Potto","Prokka","Prokki","Puahko","Puavila","Pyry","Reko","Rieti","Riku",
               "Risto","Rodi","Sampo","Satajalka","Satatieto","Savastei","Savasti","Savina","Seppo","Siila","SiitA_ri",
               "Sisoi","Sohro","Soini","Sosoi","Stjoppi","Suava","Susi","Taisto","Tapani","Tarassi","Teppana","Terho",
               "Tero","Tiihpo","Tiita","Timoi","Toivo","Toro","Triihvo","Tuokko","Turo","Tuure","Ukko","Ulaska","Ulljoi",
               "Uoti","Urho","Usti","VA_inO_","Vakko","Valassi","Valta","Valteri","Valto","Vaslei","Veledi","Veli",
               "Vesa","Vihtora","Voitto","Vuavila","YrjO_","Zakki"],
               ["dynn_Akseli","dynn_Anser","dynn_Anttonen","dynn_Bottii","dynn_Chasim","dynn_Engo","dynn_Hannus",
                "dynn_Harviala","dynn_Ilkka","dynn_Isotalo","dynn_JA_rvinen","dynn_Jaakkola","dynn_Kadomo",
                "dynn_Kangas","dynn_Karp","dynn_Karpela","dynn_Kemeloe","dynn_Kielit","dynn_Kirjala","dynn_Kneesma",
                "dynn_Kodmin","dynn_Koskinen","dynn_Kovoda","dynn_Kumo","dynn_Kurees","dynn_Kurki","dynn_Kuyto",
                "dynn_Lagoda","dynn_Lahtinen","dynn_Laine","dynn_Lalli","dynn_Lankinen","dynn_Lauri","dynn_Lepo",
                "dynn_Lonooen","dynn_MA_kelA_","dynn_Markonen","dynn_Maselke","dynn_Maunu","dynn_Neem","dynn_Nieminen",
                "dynn_Nikissima","dynn_Onega","dynn_Peelsina","dynn_Pesoesna","dynn_Pitsa","dynn_Poosa","dynn_Pudoa",
                "dynn_Rova","dynn_SA_rkilahti","dynn_Salotisa","dynn_Sarvilahti","dynn_Sepp","dynn_Sheksna",
                "dynn_Solosti","dynn_Soute","dynn_Suda","dynn_Suensaari","dynn_Syas","dynn_SydA_nmaa","dynn_Tammpere",
                "dynn_Tavast","dynn_Tuure","dynn_Ulsui","dynn_Usga","dynn_Ussa","dynn_Vaga","dynn_Vango","dynn_Vasin",
                "dynn_Veislena","dynn_Velva","dynn_Vingeli","dynn_Vuoksi","dynn_Yaga","dynn_Yensu","dynn_Yisogda",
                "dynn_Ziranni"],
               father_name_chance = 0.0,
               grandfather_name_chance = 0.0,
              )
merya = Culture('merya',
               ["Alyok","Andryu","Andyamo","Artyo","Atyamas","Azyren","Chichayka","Chipaz","Chumbulat","Dergun",
                "Deryab","Dobrinya","Doro","Drigo","Erziya","Inzhay","Kardaz","Kariton","Kezhapa","Kezhay",
                "Kezhedey","Kezhevat","Khoddey","Kichay","Kinyak","Kiryo","Koma","Koshel","Kubrat","Kvedor",
                "Kvilyo","Malyaka","Malyy","Matyo","Meltsayka","Mikikor","Mordvinko","Moksha","Mosey","Murunza",
                "Nalka","Naruchad","Nekhot","Nishkepaz","Nuyaksha","Nuyanza","Nuyat","Obran","Onton","Orunza",
                "Ovtay","Pakstyan","Paksyay","Paksyut","Parush","Pinyas","Pivtsay","Pokshayka","Puresh","Purysho",
                "Putyayka","Saksa","Setyamka","Shindyay","Shkay","Shoksha","Sokhron","Surt","Syrka","Tikshayka",
                "Torkan","Tul","Tunya","Tutyra","Tylmache","Tylze","Tyueykezhut","Tyushten","Tyushtya","Uchva",
                "Uzhara","Varaka","Varmanpaz","Vasyuk","Vechkas","Velmayka","Vikay","Virdyan","Viryas","Viryay"],
               ["dynn_Kotoro","dynn_Solono","dynn_Tebsa","dynn_Veks","dynn_Vokso","dynn_Vashu","dynn_Kernay",
                "dynn_Sutya","dynn_Neri","dynn_Saozer","dynn_Stenko","dynn_Sakhta","dynn_Ryumni","dynn_Pulok",
                "dynn_Kichma","dynn_Shacha","dynn_Khabal","dynn_Ingar","dynn_Yubil"],
               father_name_chance = 0.0,
               grandfather_name_chance = 0.0,
              )
muroma = Culture('muroma',
                ["Alyok","Aydush","Aygobek","Ayplat","Azyren","Chichayka","Chotkar","Dergun","Deryab","Echan","Elyksan",
                 "Evdyuk","Ilip","Izerge","Izi","Kavri","KU_rntnypatyr","Kystynchi","Laidemyr","Lapkas","Maska","Mikal",
                 "Miklai","Mikypyr","Mitryai","Nekhot","Nishkepaz","Nuyat","Opanas","Osherge","Ozanay","Pakstyan",
                 "Pinyas","Pokshayka","Saksa","Shindyay","Shemvuy","Shkay","Shoksha","Shumat","Sokhron","Stapan",
                 "Surt","Torkan","Tunya","Tylze","Tyushten","Tyushtya","Uchva","Uzhara","Varaka","Varash",
                 "Varmanpaz","VO_dyr","Vasyuk","Vechkas","Velmayka","Vikay","Viryas","Yamshan","Yapyk","Yolagay",
                 "YU_kserge","Yumpatyr","YU_shterge"],
                ["dynn_Cheremis","dynn_Cirmes","dynn_Kokshag","dynn_Yoshkar","dynn_Vezlom","dynn_Sanda","dynn_Sheska",
                 "dynn_Silik","dynn_Luns","dynn_Linta","dynn_Lopota","dynn_Redne","dynn_Keryet","dynn_Lamna",
                 "dynn_Maza","dynn_Lujyar","dynn_Kokchag","dynn_Mazars","dynn_Pishta","dynn_Vongus","dynn_Kundysh",
                 "dynn_Veltuk"],
                father_name_chance = 0.0,
                grandfather_name_chance = 0.0,
               )
meshchera = Culture('meshchera',
                ["Alyok","Aydush","Aygobek","Ayplat","Azyren","Chichayka","Chotkar","Dergun","Deryab","Echan","Elyksan",
                 "Evdyuk","Ilip","Izerge","Izi","Kavri","KU_rntnypatyr","Kystynchi","Laidemyr","Lapkas","Maska","Mikal",
                 "Miklai","Mikypyr","Mitryai","Nekhot","Nishkepaz","Nuyat","Opanas","Osherge","Ozanay","Pakstyan",
                 "Pinyas","Pokshayka","Saksa","Shindyay","Shemvuy","Shkay","Shoksha","Shumat","Sokhron","Stapan",
                 "Surt","Torkan","Tunya","Tylze","Tyushten","Tyushtya","Uchva","Uzhara","Varaka","Varash","Varmanpaz",
                 "VO_dyr","Vasyuk","Vechkas","Velmayka","Vikay","Viryas","Yamshan","Yapyk","Yolagay","YU_kserge",
                 "Yumpatyr","YU_shterge"],
                ["dynn_Okain","dynn_Tesha","dynn_Seres","dynn_Lyush","dynn_Ilven","dynn_Sorkor","dynn_Dubol",
                 "dynn_Lebedi","dynn_Pra","dynn_Zadey","dynn_Perki","dynn_Solosh","dynn_Otok","dynn_Luko","dynn_Voja",
                 "dynn_Tsnan","dynn_Senka","dynn_Olkhi","dynn_Susha","dynn_Voronor","dynn_Uupa"],
                father_name_chance = 0.0,
                grandfather_name_chance = 0.0,
               )
mari = Culture('mari',
                ["Alyok","Andryu","Andyamo","Artyo","Atyamas","Azyren","Chichayka","Chipaz","Chumbulat","Dergun",
                 "Deryab","Dobrinya","Doro","Drigo","Erziya","Inzhay","Kardaz","Kariton","Kezhapa","Kezhay","Kezhedey",
                 "Kezhevat","Khoddey","Kichay","Kinyak","Kiryo","Koma","Koshel","Kubrat","Kvedor","Kvilyo","Malyaka",
                 "Malyy","Matyo","Meltsayka","Mikikor","Mordvinko","Moksha","Mosey","Murunza","Nalka","Naruchad",
                 "Nekhot","Nishkepaz","Nuyaksha","Nuyat","Obran","Onton","Orunza","Ovtay","Pakstyan","Paksyay",
                 "Paksyut","Parush","Pinyas","Pivtsay","Pokshayka","Puresh","Purysho","Putyayka","Saksa",
                 "Setyamka","Shindyay","Shkay","Shoksha","Sokhron","Surt","Syrka","Torkan","Tul","Tunya",
                 "Tutyra","Tylmache","Tylze","Tyueykezhut","Tyushten","Tyushtya","Uchva","Uzhara","Varaka",
                 "Varmanpaz","Vasyuk","Vechkas","Velmayka","Vikay","Virdyan","Viryas","Viryay"],
                ["dynn_Cheremis","dynn_Cirmes","dynn_Kokshag","dynn_Yoshkar","dynn_Vezlom","dynn_Sanda","dynn_Sheska",
                 "dynn_Silik","dynn_Luns","dynn_Linta","dynn_Lopota","dynn_Redne","dynn_Keryet","dynn_Lamna",
                 "dynn_Maza","dynn_Lujyar","dynn_Kokchag","dynn_Mazars","dynn_Pishta","dynn_Vongus","dynn_Kundysh",
                 "dynn_Veltuk"],
                father_name_chance = 0.0,
                grandfather_name_chance = 0.0,
               )
mordvin = Culture('mordvin',
                ["Alyok","Andryu","Andyamo","Artyo","Atyamas","Azyren","Chichayka","Chipaz","Chumbulat","Dergun",
                 "Deryab","Dobrinya","Doro","Drigo","Erziya","Inzhay","Kardaz","Kariton","Kezhapa","Kezhay","Kezhedey",
                 "Kezhevat","Khoddey","Kichay","Kinyak","Kiryo","Koma","Koshel","Kubrat","Kvedor","Kvilyo","Malyaka",
                 "Malyy","Matyo","Meltsayka","Mikikor","Mordvinko","Moksha","Mosey","Murunza","Nalka","Naruchad",
                 "Nekhot","Nishkepaz","Nuyaksha","Nuyanza","Nuyat","Obran","Onton","Orunza","Ovtay","Pakstyan",
                 "Paksyay","Paksyut","Parush","Pinyas","Pivtsay","Pokshayka","Puresh","Purysho","Putyayka","Saksa",
                 "Setyamka","Shindyay","Shkay","Shoksha","Sokhron","Surt","Syrka","Tikshayka","Torkan","Tul","Tunya",
                 "Tutyra","Tylmache","Tylze","Tyueykezhut","Tyushten","Tyushtya","Uchva","Uzhara","Varaka","Varmanpaz",
                 "Vasyuk","Vechkas","Velmayka","Vikay","Virdyan","Viryas","Viryay"],
                ["dynn_Chumbulatid","dynn_Purginepazid","dynn_Varakid","dynn_Rav","dynn_Paas","dynn_Shkai",
                 "dynn_Mastoratia","dynn_Chipaz","dynn_Nishkepaz","dynn_Ange_Patiai","dynn_Mastoron_Kirdi",
                 "dynn_Shkay","dynn_Kardaz-Scrko","dynn_Tushtyan","dynn_Aidar","dynn_Borovon","dynn_Derkul","dynn_Valo"],
                father_name_chance = 0.0,
                grandfather_name_chance = 0.0,
               )
mogyer = Culture('mogyer',
                ["A_bel","A_dA_rn","A_goston","A_lmos","A_rpA_d","O_dO_n","Alajos","Ambrus","AndrA_s","Antal","Attila",
                 "BA_lint","BE_la","BalA_zs","Benedek","BernA_t","BertO_k","Bertalan","BoldizsA_r","Bonuslo","Borisz",
                 "CsA_k","Csaba","Csongor","DE_nes","DO_mO_tO_r","DezsO_","DomoszlO_","DonA_t","Elek","ElemE_r","Endre",
                 "ErnO_","FulO_p","Ferenc","Frigyes","GA_bor","GA_briel","GA_spA_r","GE_za","Gazsi","GellE_rt","Gergely",
                 "GyO_rgy","Gyula","Imre","IstvA_n","IzsA_k","JA_kob","JA_nos","JO_zsef","JenO_","KA_lmA_n","KA_roly",
                 "KonrA_d","KornE_l","KristO_f","LA_szlO_","LA_zA_r","LO_rinc","Lajos","Lampert","Levente","LukA_cs",
                 "MA_rk","MA_rton","MA_tE_","MA_tyA_s","MO_ric","MO_zes","MihA_ly","MiklO_s","NA_ndor","OrbA_n",
                 "OszkA_r","PA_l","PE_ter","SA_muel","SA_ndor","Salamon","Saul","Soma","Szilveszter","TA_dor",
                 "Tacsony","TamA_s","Tibor","Tivadar","Vazul","Vencel","Vilmos","ZoltA_n","Zsigmond","Zsolt"],
                ["dynn_A_rpA_dy","dynn_CsA_szA_r","dynn_Vajlok","dynn_KA_n","dynn_Omodej","dynn_Zapolsky","dynn_Drugeth",
                 "dynn_Csak","dynn_Pallfy","dynn_Apafi","dynn_BA_nffy","dynn_BerzE_nyi","dynn_Bocskai","dynn_Borsa",
                 "dynn_CzirA_ky","dynn_Debreceni","dynn_DerencsE_nyi","dynn_DiO_szegi","dynn_DO_ry","dynn_EgervA_ri",
                 "dynn_ForgA_ch","dynn_Garai","dynn_PA_lO_czi","dynn_HE_dervA_ri","dynn_Hunyadi","dynn_KA_n",
                 "dynn_KA_rolyi","dynn_KO_szegi","dynn_Kun","dynn_Losonczi","dynn_MarO_ti","dynn_PerE_nyi",
                 "dynn_RA_tO_t","dynn_Rozgonyi","dynn_Szakoly","dynn_SzE_csE_nyi","dynn_SzE_chy","dynn_Telegdi",
                 "dynn_ThurzO_","dynn_U_jlaki","dynn_Kanizsai","dynn_Meggyesi","dynn_Osli","dynn_Viczay",
                 "dynn_Balassa","dynn_BA_thory","dynn_KA_lnoky","dynn_Niedzica","dynn_ZA_polya","dynn_SzE_kely",
                 "dynn_DO_zsa","dynn_Apafi","dynn_Balassi","dynn_Bethlen_von_IktA_r","dynn_Budai_Nagy","dynn_Celko",
                 "dynn_Corvinus","dynn_DA_vid","dynn_DE_csey","dynn_ME_zesi","dynn_Draskovich","dynn_ErdO_dy",
                 "dynn_RE_vay","dynn_DuruZ_mic","dynn_Szemere","dynn_Hadik","dynn_BatthyA_ny","dynn_Csesznegi",
                 "dynn_EsterhA_zy","dynn_HajdU_","dynn_JesenskY_","dynn_Medveczky","dynn_RA_kO_czi",
                 "dynn_Wass_de_Czege","dynn_Szapolyai","dynn_Zichy","dynn_Zrinski"],
                father_name_chance = 0.0,
                grandfather_name_chance = 0.0,
               )
gorkhovo = copy.deepcopy(mogyer); gorkhovo.name = 'gorkhovo'
sargat = copy.deepcopy(mogyer); sargat.name = 'sargat'
khanty = Culture('khanty',
                ["Andyamo","Arnaz","Arti","Artis","Arvo","Aymort","Azeg","Biur","Biyar","Burmort","Chichayka","Chuga",
                 "Dergun","Deryab","Dobrinya","Dokya","Dondy","Gazheg","Hulyen","Inzhay","Irter","Lyneg","Lysko",
                 "Kezhapa","Kezhay","Kezhedey","Kezhevat","Kichay","Koksha","Kuaz","Kudym-Osh","Kya","Kyldysin",
                 "Malyaka","Malyy","Meltsayka","Mosheg","Nalka","Nuyaksha","Nuyanza","Nuyat","Nydog","Nylog","Odeg",
                 "Onika","Osh","Oshmar","Oshypel","Ovtay","Ozheg","Ozhmeg","Pakstyan","Paksyay","Paksyut","Parush",
                 "Pivtsay","Pokshayka","Putyayka","Pyera","Rateg","Rayda","Sarin","Sektev","Setyamka","Shindyay",
                 "Shypicha","Shyrpuzh","Spira","Syrka","Tikshayka","Tuhan","Tyueykezhut","Tyutyuk","Tugan","Turush",
                 "Uchva","Varaka","Vechkas","Velmayka","Virdyan","Viryas","Viryay","Vokan","Yirkap","Ylvan","Zarny",
                 "Zhebeg","Zhuneg","Zyryan"],
                ["dynn_Mansi","dynn_Oborin","dynn_Ketkso","dynn_Vakhad","dynn_Chulyman","dynn_Tomto","dynn_Katunnu",
                 "dynn_Anuya","dynn_Irtys","dynn_Omno","dynn_Tobolon","dynn_Tavdai","dynn_Isetu","dynn_Miassar",
                 "dynn_Ubaganor","dynn_Kondair","dynn_Kazymil","dynn_Yugan","dynn_Nakharva","dynn_Turunt",
                 "dynn_Pandey","dynn_Kalmoti","dynn_Mamkin","dynn_Voyetor","dynn_Enetor","dynn_Toptyodyn",
                 "dynn_Yendra","dynn_Dolgi","dynn_Vaspukhol","dynn_Tymgym","dynn_Elizaro","dynn_Karapau",
                 "dynn_Nyartu","dynn_Lokhto","dynn_Lakhsentur","dynn_Tuman"],
                father_name_chance = 0.0,
                grandfather_name_chance = 0.0,
               )

samoyed = Culture('samoyed',
                ["Alik","Hasaba","Kako","Kharuchi","Kolik","Mandak","Nabtiko","Nenyts","Nga","NgE_noh","Noumea","Num",
                 "Nyalku","Panay","Pudak","Salinder","Samatu","Sarak","Sirtya","Somatu","Syudbya","Tatva","Tolik",
                 "Vesei","Wayngachi","XE_ryuchi","Yadne","Yapti","Yar","Yavlad","Yurak"],
                ["dynn_Varakid","dynn_Sarakid","dynn_Hasabid","dynn_Tatvid","dynn_Yurakid","dynn_Kuluio","dynn_Dvinid",
                 "dynn_Onegin","dynn_Uspinega","dynn_Pinega","dynn_Maugra","dynn_Osil","dynn_Yagani","dynn_Myando",
                 "dynn_Vezmo","dynn_Muraka","dynn_Pusko","dynn_Kudmi","dynn_Ukhta"],
                father_name_chance = 0.0,
                grandfather_name_chance = 0.0,
               )
yeniseian = Culture('yeniseian',
                ["Bokkok","Rek","Bukrek","Yeyiyu","Gwang","Qang","Khum","Krang","Qiyijia","Qrah","Koumi","Beye","Sening",
                 "Es","Balma","Togeta","Belegin","Tums","Chip","Kit","Bok","Aqtasi","Hig","Pikhe","Qahi","Kar","Konnong",
                 "Sulams","Kruglais","Kisla","Tis","Chis","Hoksi","Ses","Soga","Hols","Tuki","Kamara","Tig","Onkhoi",
                 "Haksem","Pacham","Tor","Bey"],
                ["dynn_Bukrek","dynn_Bokkok","dynn_Khum","dynn_Qiyijia","dynn_Koumi","dynn_Sening","dynn_Togeta",
                 "dynn_Belegin","dynn_Aqtasi","dynn_Konnong"],
                father_name_chance = 0.0,
                grandfather_name_chance = 0.0,
               )
tungusic = Culture('tungusic', #Really Jurchen
                ["Abaohan","Abulang","Agu","Aguda","Agunai","Aguo","Aha","Ahacu","Ahai","Ahaibaifu","AiS_I_","AiS_I_ha",
                 "Ajungha","AlbasE_ri","Ali","Alihan","Alihemen","Alin","Alu","Alubu","Aludai","Aluhan","Aluobuhua",
                 "Aluwan","Ancen","Ancu","Andahai","Aodi","Asur","AS_entan","AS_I_ngha","Bahai","Bahei","Bahulu",
                 "Baifu","Baoci","Baohuoli","Barha","Beilu","Biefoga","Bugil","Bulo","BulE_gE_maihu","Cala","Cangho",
                 "Caoha","CenhulagE_","Cotoya","Cunggelo","CE_gE_","CE_jE_","CE_ndapan","CE_nhulagE_","Daijuhu",
                 "Daisu","Dalunha","DaS_I_n","Digunai","Diku","Dili","Diligi","Dingge","Dingju","DiS_un","Dorbi",
                 "Dumu","DuS_i","Dzhin","Ecu","Eiyeku","EiE_lu","Eliduo","Elu","Elubu","Eluguan","Elun","Fanca",
                 "Fannu","FE_nsI_","GiahucI_","Giohua","Gioli","Guantu","Gulan","GuS_a","GE_cI_buhua","GE_jeE_",
                 "Hacaha","Hadar","Hanpu","HanS_I_","HasaiE_","HaE_u","Heda","Hela","Helibo","Hesun","Heye",
                 "Hezhe","Hezhenbao","HeS_i","HeS_itan","HuboS_u","Hudun","Huihou","Hulijia","Hulu","Hulubu",
                 "Hushahu","Hushida","Husurugai","HusurE_gai","Hutunla","Hutuwa","HuC_ienu","HuS_a","Ibaha",
                 "IcI_gE_","IhalacI_","Iji","Ilungha","Inginggia","IngjI_na","IrnurE_u","IS_iha","Jabingia",
                 "Jahodai","Jahudai","Jaligi","Jogosang","Juguta","JulE_","JI_lunggusu","Kunaha","Kunuma",
                 "KuS_inu","Labuda","Loloho","LouS_i","Manduhe","Mangda","Mapo","Meng_an","Mentemu","MieS_I_nu",
                 "Moliye","Muha","Mutalu","Mutawuta","ME_deE__E_","NaduoS_I_","Nanhe","Nianhan","NibucI_","NigE_",
                 "NijE_ngE_","Ninggisa","Ninggujua","Ningji","Ningjiasu","NudE_gE_","Nuhu","NujE_nge","NU_linai",
                 "OhE_nE_gE_","Oon","Pandu","PociS_u","Pudu","Puladu","Pulihei","Puluhu","Pusulie","Sagai",
                 "Sagezhou","SahamieE_","Sahani","Saiha","Sain","Salinian","SatS_I_","Soli","Songge","Sonu",
                 "Souru","Suike","Sungida","SI_aoha","Tege","Telin","Tudu","Tugesu","Tunon","TuS_I_nge","Cala",
                 "CI_nu","Uda","Udaun","Udisa_E_","UhuwE_","Ulu","US_I_nha","WeiC_in","Wennu","Woben","Wodai",
                 "Wohu","Wolibu","Wolie","Woli_an","Wolu","Wolun","Wosai","Woye","Wozhe","Wucimai","Wudubu",
                 "Wugucu","Wugunai","Wulie","WuyaS_u","Wuzhu","WE_uanjE_","YacI_nggia","Yangdai","Yangha",
                 "Yangmudau","Yansun","Yawuta","Yingge","Yinzhuke","Yongji","Yunji","Zhanmeihe","ZhuS_ennu",
                 "E_lijesE_nE_","E_ncI_E_ng","E_surE_ku","E_tE_","S_alungha","S_angnggu","S_engguo","S_ensi_abu",
                 "S_entumen","S_iebucu","S_iekude","S_ielihu","S_ielu","S_ieyibao","S_igiyanu","S_igunai","S_ijianu",
                 "S_ilu","S_ilula","S_inde","S_inilie","S_iS_ihuan","S_unian","S_untC_ing","S_I_bua","S_I_langha",
                 "S_I_lu","S_I_lungha","S_I_ngsI_","S_I_puni"],
                ["dynn_Haixi","dynn_Jilin","dynn_Odori","dynn_Amgun","dynn_Suksuhu","dynn_Mengtemu","dynn_Khingan",
                 "dynn_Wanyan","dynn_Ahanba","dynn_AiS_I_n","dynn_Aotun","dynn_Atai","dynn_BujowA_","dynn_Juhung",
                 "dynn_A_luA_","dynn_Fojomon","dynn_FuC_ian","dynn_Giagu","dynn_Giaoru","dynn_Guaiuruan",
                 "dynn_HA_rsurgia","dynn_HA_S_I_riA_","dynn_MA_nin","dynn_Nahu","dynn_Sahala","dynn_S_aron",
                 "dynn_S_I_jan","dynn_Jang","dynn_Tukdan","dynn_CA_ncun","dynn_Ugueisun","dynn_Ulyan","dynn_UndihA_n",
                 "dynn_Usaye","dynn_WangsurA_wei","dynn_Wongian","dynn_Wangiyyan","dynn_Nalan","dynn_Tushan",
                 "dynn_Pusan","dynn_S_uhu","dynn_Wugulun","dynn_Tangkuo","dynn_Wendihen","dynn_Wusazha","dynn_Pucha",
                 "dynn_Peiman","dynn_Wulinda","dynn_Tudan","dynn_HeS_ilie","dynn_Dilie","dynn_Ikderi","dynn_Aolimi",
                 "dynn_Puali","dynn_Yuelidu","dynn_Tieli","dynn_Punuli","dynn_Odoli","dynn_Huligai","dynn_Tuowen",
                 "dynn_Nianhe","dynn_S_uyaojia"],
                father_name_chance = 0.0,
                grandfather_name_chance = 0.0,
               )

suebi = Culture('suebi',
               ["Abbelin","Abragast","Abrekan","Adorik","Agriulfum","Agriwulf","Aiwarik","Alamir","Aldered","Alduward",
               "Aliverk","Allifred","Alowind","Alvar","Amalarik","Amedon","Anila","Ardabast","Ardald","Ardebred",
               "Ardulf","Argilo","Argivast","Ariamir","Arias","Ariast","Arnald","Askarik","Askulf","Athalfons","Attila",
               "Audekka","Audikka","Badamund","Badesind","Badila","Bagino","Bakkina","Baldemir","Baldesind","Baltar",
               "Balto","Baril","Bati","Baton","Bazar","Bekkilla","Bela","Belesar","Berosind","Blandila","Bliviarik",
               "Bonemir","Burgila","Crizila","Dada","Dadila","Dadinus","Danila","Desterik","Dokemir","Domerik","Dukila",
               "Dulkemir","Dulkemund","Eborik","Eimorik","Eldan","Eldegeses","Eldemir","Eldemund","Eldesind","Eldibert",
               "Eldin","Eldiverik","Eldo","Eldowig","Ellekka","Elpandus","Elperik","Emiso","Endulf","Entrud","Erifuns",
               "Ermaldus","Ermarik","Ermefred","Ermegild","Ermemir","Ermiar","Ermila","Eruulfus","Espallo","Faffila",
               "Fagila","Fagildus","Fakino","Fakko","Fandila","Fannus","Fatered","Fatu","Felellus","Felemir","Filibert",
               "Filon","Floresind","Fofo","Fonso","Fralenko","Framilla","Framta","Frankila","Franko","Frariko",
               "Frauwino","Fredamund","Fredemir","Fredenand","Frederik","Fredisk","Fredowald","Fredowin","Fredulf",
               "Fredus","Freduwar","Fridibert","Frogila","Frogiulf","Froila","Frojo","Fronosila","Frowarenk","Frumar",
               "Frumir","Frunila","Fruwarik","Fulkared","Gademir","Gaella","Gaffo","Gagikka","Gaidus","Gaifar","Ganati",
               "Gandila","Gandinus","Gandulf","Ganila","Ganoi","Garding","Gastre","Gaton","Gaudemir","Gauderik",
               "Gaudesind","Gaudila","Gaudilani","Gaudinas","Gaufred","Gaulf","Gavila","Gebuld","Geda","Gega","Geldemir",
               "Gelmir","Gemund","Gendo","Genila","Genlo","Gentoi","Gera","Germund","Gero","Gesa","Gesemir","Geserik",
               "Gesulf","Geterik","Getila","Gidibert","Gigel","Gildarik","Gildo","Gilloi","Girald","Gismund","Gisofred",
               "Gisvad","Gitarius","Gitesind","Gitio","Givellan","Gladila","Godefred","Godegild","Godellus","Godemir",
               "Godesind","Godomund","Gogila","Gogitus","Goldegild","Goldred","Goldregod","Golfarik","Golinus","Gollo",
               "Gomald","Gomared","Gomarik","Gomedei","Gomesind","Gomulf","Gomund","Gonso","Gontemund","Gontere",
               "Gontoi","Gontuwald","Gotesend","Goto","Goton","Goymund","Gramila","Granilo","Gresomar","Grima",
               "Grisulf","Grundemar","Gudegis","Gudenand","Gudered","Guderik","Gudesind","Gudestes","Gudila","Gudilo",
               "Gudilulf","Guginus","Guldar","Gulderes","Gulderik","Gulfar","Gulfemir","Gumar","Gumel","Gumila","Gumito",
               "Gundarius","Gundebred","Gundelin","Gunderam","Gunderik","Gundesila","Gundesind","Gundifort","Gundila",
               "Gundisalf","Gundiskalk","Gundivad","Gundivald","Gundon","Gundulf","Gunkitus","Guntato","Guntellus",
               "Guntemir","Gunterotis","Guntiesklo","Guntikio","Gutemir","Gutemund","Gutila","Gutinus","Gutumar",
               "Guwalamar","Guwalamir","Guwaldar","Guwaldejo","Guwaldramir","Guwandalar","Guwandalisko","Guwandila",
               "Guwantal","Guwimarik","Gwendo","Gwilbert","Gwimir","Gwina","Gwinus","Gwirik","Gwisind","Hamdino",
               "Heremigar","Hermekisk","Hermerik","Herus","Hidibert","Hildebrad","Hildefuns","Hildemir","Hilderik",
               "Hildowi","Hildras","Hildulfus","Hitault","Hitimund","Hlewomir","Hlutar","Hunimund","Igo","Ikila",
               "Indisk","Itila","Ivolik","Janard","Jenserik","Jerulf","Jonarik","Jonila","Justiarik","Justri",
               "Juswandus","Kagild","Kagitus","Kalendus","Kamund","Kanut","Kararik","Karlo","Karmir","Kartin",
               "Kedisilo","Keila","Kendas","Kendemir","Kendered","Kendon","Kendulf","Ketenand","Keti","Ketoi",
               "Koniarik","Kwalavala","Kwedesend","Kwedulf","Kwella","Kwidemir","Kwiderik","Kwintila","Kwintilo",
               "Kwitarius","Kwitoi","Kwitre","Lalla","Lallinus","Lallus","Lilo","Liubald","Liubegild","Liubegoto",
               "Liubegutus","Liubellus","Liubered","Liuberik","Liubert","Liubesind","Liubila","Liubilo","Liubus",
               "Lovoi","Lubinus","Magan","Magila","Magit","Magnit","Malared","Malarik","Malasko","Maldras","Mandila",
               "Mandin","Mandulf","Manello","Maniarik","Manilla","Maninus","Maniulf","Manna","Manno","Manosind",
               "Manowim","Mantellus","Manulf","Manuwald","Markitus","Marko","Markosind","Martila","Masdras","Massila",
               "Materiks","Matroi","Matrosind","Mauran","Maurentan","Maurikan","Mauron","Megild","Meitila","Meitins",
               "Meitulf","Merila","Mervig","Miro","Mirosind","Miruwaldo","Moderid","Moderik","Modila","Modild","Monderik",
               "Mondoi","Monefuns","Monobred","Mudarjo","Mudila","Mund","Mundel","Mundila","Munisk","Naustila","Neufila",
               "Nitigis","Niufila","Notar","Nwilla","Nwillo","Odorik","Ofila","Oldarik","Onared","Onegildo","Onemir",
               "Onesind","Onorik","Oppa","Oppila","Osdulf","Osmund","Pantar","Pantin","Panto","Pappo","Pennino","Pepi",
               "Pipernik","Rademund","Radesind","Radulf","Ragesind","Ragian","Ragifred","Ragimir","Ragito","Ragolf",
               "Raiola","Rakerik","Ramila","Ramon","Ramulo","Ranar","Randemir","Randila","Rando","Randuwar","Ranemir",
               "Ranemund","Ranibert","Ranilo","Ranisk","Ranosind","Ranulf","Ranuwald","Ratar","Raupar","Redemir",
               "Refulfo","Regaulf","Reginald","Reimund","Reirik","Rekkafred","Rekkared","Rekkela","Rekkemir","Rekkemund",
               "Rekkerit","Rekkesind","Rekkeswind","Rekkiar","Rekkila","Rekkilod","Rekkimund","Rekkoi","Rekkuwald",
               "Remegild","Remesar","Remesila","Remesind","Remest","Remismund","Remisol","Renderik","Resterik","Reterik",
               "Rikkigar","Rodebert","Rodemir","Rodowug","Romarik","Romila","Rososild","Ruderik","Rudesind","Rudila",
               "Rudilo","Rufred","Rulind","Sabared","Sabegoto","Sabila","Sabitus","Sagatus","Sagild","Sagulf","Salamir",
               "Salla","Sandimir","Santimir","Saroi","Saruwila","Savarik","Savegod","Savoi","Sawarak","Saxo","Sedeges",
               "Sedino","Segemund","Segesind","Segestro","Segga","Segika","Segimar","Segio","Segioi","Seguwin",
               "Seixomir","Selmir","Seloi","Senda","Sendamir","Sendel","Senderik","Sendin","Sendoi","Sendon","Sendred",
               "Sendulf","Senduwitu","Seniared","Seniulf","Senta","Sentar","Senuldo","Seririgo","Serulf","Servald",
               "Seserik","Seskut","Sesmir","Sesmund","Sesoi","Sesuwito","Sevegild","Sigebert","Sigefrid","Sigered",
               "Sigerik","Sigesind","Sigila","Sigu","Sigunterik","Sindamund","Sindibert","Sindigis","Sindila","Sindilo",
               "Sindo","Sinifred","Sisebut","Sisel","Sisibert","Sisil","Sisila","Sisilu","Sisinus","Sisnand","Sisuld",
               "Sisulf","Sisuwald","Sitagel","Siti","Sitivid","Skapa","Skarkila","Skerin","Smerlo","Sonegild","Songimer",
               "Soniarik","Sonifred","Sonna","Sontrila","Spanar","Spanarik","Spandarik","Spanilo","Spanosind","Sperautan",
               "Spintilo","Spodemir","Spoderik","Struko","Sundemir","Suniagisk","Suniar","Sunila","Sunilo","Sunimir",
               "Sunitus","Suwabas","Suwavar","Suwered","Suwimir","Tandus","Tankila","Tankin","Tankus","Tankwila","Tata",
               "Teadario","Tedoi","Tegila","Tegino","Tegio","Tegit","Teobald","Teoda","Teodebert","Teodefred","Teodegild",
               "Teodekut","Teodemir","Teodemund","Teodenand","Teoderad","Teoderik","Teodesind","Teodevad","Teodila",
               "Teodilo","Teodinus","Teodisila","Teodisk","Teodiskes","Teodiu","Teoduldo","Teodulf","Teton","Titila",
               "Torsario","Tota","Tradin","Tradus","Trakin","Trasar","Trasarik","Trasendus","Trasido","Trasiuwadus",
               "Trasmiro","Trasmund","Trasoi","Trassemut","Trastalo","Trastemir","Trastulf","Trasulf","Trasuwar",
               "Trevuls","Trudigild","Trudilo","Trudinus","Trudulf","Truktemir","Truktemund","Trukterik","Truktesind",
               "Truktila","Truktin","Truktus","Truwitellus","Truwitero","Tumtuldo","Tundulfus","Tuntila","Turisulf",
               "Unemund","Unila","Unisk","Usegild","Valaris","Vamba","Vandino","Vasaridus","Vederoi","Vedragese",
               "Venedario","Venetrik","Venze","Vermund","Viamund","Viarik","Vidragild","Vidrald","Vidramir","Vidubas",
               "Vigila","Vigilo","Vigiltu","Vigoi","Viktemir","Vikterik","Vilesind","Vilian","Viliar","Viliarik",
               "Vilifred","Vilifuns","Viligus","Villelmus","Villiamir","Villo","Viman","Visald","Visandus","Visellu",
               "Visklafred","Visklamir","Visklamund","Visklario","Vistemund","Visterlo","Vistesind","Vistibert",
               "Vistiklo","Vistragild","Vistramund","Vistrarik","Vistremir","Vistresind","Vitar","Vitas","Vitila",
               "Vitildus","Vitinus","Vitisk","Vitiza","Viza","Vizamund","Vizila","Vizoi","Vuwanda","Wadamund","Wademir",
               "Wegitus","Weremund","Wiliared","Willoi","Wimared","Wistiz","Wistrela","Wisulf","Wita","Wittimer",
               "Zazitus","Zazo","Zendasind","Zenzitus","Zisila"],
               ["dynn_Hemering","dynn_Isiding","dynn_Masdring","dynn_Rechimundus","dynn_Rechling","dynn_Suev","dynn_Theoning"],
               father_name_chance = 0.1,
               grandfather_name_chance = 0.5,
              )
langobard = Culture('langobard',
               ["Abbo","Adelbert","Adaldag","Adalhard","Adelard","Aega","Agilbert","Agobard","Aigulf","Alberic",
               "Allowin","Amalricus","Amand","Amator","Angegisis","Angilbart","Angilbert","Anno","Ansegisel",
               "Anskar","Arbitio","Arbogast","Arbogastes","Arculf","Arnoul","Arnulf","Artaud","Asselin","Atacinus",
               "Audoen","Audomar","Audoneus","Audramnus","Baugulf","Bauto","Bavo","Benild","Berchar","Berengar",
               "Bernard","Berno","Bero","Bertelis","Berthaire","Bertin","Bertulf","Besso","Birinus","Blutmund","Boso",
               "Bovo","Brice","Britius","Brocard","Bruno","Burchard","Butilin","Carloman","Cassyon","Ceufroy",
               "Charibert","Charles","Cheldric","Childebert","Childebrand","Childeric","Chilperic","Chlodmer",
               "Chlodowig","Chlotar","Chrodegang","Clodomir","Clotaire","Clothair","Clovis","Corbinian","Cyr",
               "Cyricus","Dado","Dagobert","Dalfin","Dodo","Dreux","Drogo","Dudon","Ebbo","Ebroin","Ebrulf",
               "Einhard","Emme","Emmeran","Engilbert","Enurchus","Erchinoald","Evroul","Evroult","Fardulf","Faro",
               "Flodoard","Folcard","Folmar","Fredegar","Fridolin","Fridugis","Fulbert","Fulk","Fulrad","Gerbert",
               "Gereon","Gerold","Gifemund","Giseler","Giso","Godobald","Godun","Goisfrid","Goscelin","Gouzlim",
               "Gozbert","Gozolon","Grifo","Grimald","Grimbald","Gunthar","Guntramn","Hagen","Halinard","Hartmut",
               "Helinand","Helisachar","Heribert","Hildebald","Hildebold","Hildeprand","Hilduin","Hincmar","Hlodver",
               "Huebald","Humbert","Hunald","Imbert","Imninon","Jocelin","Lambert","Lanfranc","Laudus","Lebuin",
               "Ledger","Leger","Leodegar","Letard","Leufred","Leufroy","Leutfrid","Leuthere","Liudhard","Liudolf",
               "Lo","Lothar","Lul","Lull","Maiuel","Maixent","Majorian","Mallobaudes","Mansuetus","Maraulf","Marcoul",
               "Matfrid","Mauger","Me_dard","Meginhard","Merobaudes","Merovech","Nithard","Norbert","Nordbert",
               "Notker","Odger","Odo","Odulf","Omer","Orderic","Otker","Ouen","Ouus","Pacatian","Pair","Pancras",
               "Panteleon","Pepin","Philibert","Piligrim","Pippin","Poppo","Puvis","Radigis","Ragnfred","Razo",
               "Reginald","Reginar","Remi","Reolus","Richomer","Richomeres","Riquier","Rothad","Samo","Sergius",
               "Sicho","Sigebert","Sigibert","Suger","Suidbert","Suidger","Syagrius","Tassilo","Taurin","Tescelin",
               "Thankmar","The_odard","Theodoric","Theodulf","Theodulph","Theudebert","Theuderic","Theutgaud",
               "Thierry","Thietmar","Turpin","Vedast","Vicelin","Vigor","Vulmar","Waiofar","Wala","Walaric",
               "Waldolanus","Waltgaud","Wandregisel","Wandregisilus","Wandrille","Warmann","Werinbert","Wibert",
               "Wichmann","Willehad","Willibald","Willibrord","Wulfram","Zwentibold"],
               ["dynn_Langobard","dynn_Lething","dynn_Gausian","dynn_Klephing","dynn_Romaulding","dynn_Euining",
                "dynn_Artavazding","dynn_Liuting","dynn_Alaging","dynn_Auteraming","dynn_Saxing","dynn_Brunting",
                "dynn_Zabaning","dynn_Rodaning","dynn_Aming","dynn_Farualding","dynn_Ratching"],
               father_name_chance = 0.1,
               grandfather_name_chance = 0.5,
              )

norse = Culture('norse',
               ["Anundr","Arnfast","A_li","A_lfr","A_lfgeir","AndrE_s","ArnbjO_rn","ArngrI_mr","A_rni","A_sbjO_rn",
                "A__ke","A_skell","Baldr","Bersi","BjO_rn","Bragi","BuT_li","BA_rD_r","Birgir","BU_i","BO_D_var",
                "BO_tO_lfr","BrynjO_lfr","BergT_O_r","Dan","Dagr","DY_ri","Egill","Einarr","EilI_fr","Emundr",
                "EirI_kr","Eysteinn","Einar","Freyr","Fasti","FriT_rI_kr","FrIrekr","FrO_T_i","FO_lki","Flosi",
                "Geirr","GuT_mundr","GuT_rO_T_r","Gunnarr","GandA_lfr","GnU_pa","Gormr","GrI_mr","GuT_frI_T_r",
                "Grettir","Haraldr","Haukr","Helgi","Hrafn","HA__kon","Hallsteinn","Hemingr","HO_lmgeirr","HrO_lfr",
                "Hrani","HA_steinn","HjA_lmar","HrO_T_geirr","HrO_D_O_lfr","HrE_rekr","HY_singr","HalfdA_n","HerjO_lfr",
                "HO_rD_r","HO_gni","HU_nT_jO_fr","Hordaknutr","IngO_lfr","Ingimar","Ingjaldr","I_var","JA_tvarD_r",
                "JO_rundr","Karl","Kjartan","KolbjO_rn","Ketill","Ketilmundr","KnU_tr","Kollr","KA_ri","Kolbeinn",
                "LjO_tr","MagnU_s","NjA_ll","Oddr","Ormr","O_rvar","O_nundr","O_feigr","O_lafr","O_ttar","O_lvir",
                "O_gmundr","Refr","Ragnarr","RO_gnvaldr","Refill","RI_kU_lfr","Snorri","SigurT_r","StarkaT_r",
                "Steinn","Sturla","StyrbjO_rn","SumarliT_i","Suni","Sveinn","Sverker","SE_mundr","SO_lvi","SkU_li",
                "SigrbjO_rn","Sigtryggr","StyrkA_r","SO_rkvir","SkarphE_D_inn","SkjO_ldr","Tolir","T_orbjO_rn",
                "T_orbrandr","T_orsteinn","Tyke","T_iO_D_mundr","TO_ki","T_orfinnr","T_orD_r","T_orgils","T_O_rO_lfr",
                "TO_sti","T_jO_stO_lfr","Tryggvi","U_lfr","U_lfhE_D_inn","U_lfkell","Vagn","VE_mundr","Valdemar",
                "VigfU_s","ValT_jO_fr","Yngvar"],
               ["dynn_StO_rr","dynn_Borg","dynn_KrA_ka","dynn_Mikli","dynn_SmiD_r","dynn_MO_ring","dynn_GA_rdske2",
                "dynn_Trolli","dynn_Kven","dynn_Toki","dynn_HA_rde","dynn_Eyjing","dynn_Orming","dynn_GoD_i",
                "dynn_AustmaD_r","dynn_HA_vi","dynn_Rakki","dynn_Skrauti","dynn_Snarfari","dynn_Strangi","dynn_Snjalli",
                "dynn_SU_rr","dynn_SkA_ld","dynn_Viss","dynn_T_rymr","dynn_T_vari","dynn_O_lfU_ss","dynn_O_rn",
                "dynn_HvI_ti","dynn_Sterki","dynn_AuD_gi","dynn_RauD_i","dynn_Spaki","dynn_Svarti","dynn_Rammi",
                "dynn_MjO_vi","dynn_RI_ki","dynn_Lambi","dynn_Skarfr","dynn_SkA_l","dynn_Sleggja","dynn_SmjO_r",
                "dynn_Stjarna","dynn_StrU_gr","dynn_SA_lendingr","dynn_SU_rr","dynn_SA_lingr","dynn_Trausti",
                "dynn_VeD_r","dynn_VA_mU_li","dynn_VA_ni","dynn_T_istill","dynn_T_jO_fi","dynn_T_ynning",
                "dynn_Byrrnesson","dynn_VeO_y","dynn_Eirikson","dynn_Sognsdal","dynn_Gunarrson","dynn_Firdi"],
               father_name_chance = 0.0,
               grandfather_name_chance = 0.5,
              )

hunnic = Culture('hunnic',
               ["Akhad","Alburia","Alypbi","Askungur","Attila","Aybat","Balamber","Belk","Bleda","Bu-Timer","Bu-Urgan",
                "Chelbir","Dengizich","Djilka","Djurash","Ellec","Ermak","Gazan","Gostun","Hernach","Khinialon","Kurbat",
                "Kutrigur","Labertam","Octar","Rugila","Sandlikh","Shambat","Sinnion","Sulabi","Tat-Ugek","Tat-Utyak",
                "Tatra","Tingiz","Tuldila","Uldin","Uturgur","Vund","Zabergan"],
               ["dynn_AttI_lakili","dynn_Askungurili","dynn_Balamberili","dynn_Dengizichili","dynn_Kutrigurili",
                "dynn_Sandlikhili"],
               father_name_chance = 0.0,
               grandfather_name_chance = 0.0,
              )
khuni = copy.deepcopy(hunnic); khuni.name = 'khuni'
bolghar = Culture('bolghar',
               ["Almish","Alzek","Anzi","Apskhih","Araslan","Asparukh","Balamber","Bars","Bataul","Batbayan",
               "Batoya","Batulia","Bayan","Belkermak","Bezmer","Boyan","Bulger","Buzan","Chepa","Chinialush",
               "Dengizikh","Dizeng","Dometa","Dristar","Drong","Dukum","Ellak","Elemag","Ernakh","Eskhakh",
               "Goleda","Gostun","Guar","Hudbad","Iani","Irnek","Isbul","Islivan","Isperikh","Ispor","KA_laC_",
               "Kano","Karan","Karaton","Kardam","Kharaton","Khinialon","Khudbard","Kordil","Kormesiy","Kormisosh",
               "Kotrag","Krovat","Krum","Kuber","Kubrat","Kurt","Kutrigur","Kuvrat","Labertam","Magotin","Malamir",
               "Mugel","Odolgan","Okhsi","Okhsun","Okors","Omurtag","Onegavon","Organ","Organa","Ornag","Oshi",
               "Ostro","Pagan","Pakhtiyar","PavA_l","Praksa","Rassate","Rugila","Sabin","Sandil","Sandilkh",
               "Sarkhan","SartA_C_","Savin","Sevar","Shilki","Sondoke","TA_htaman","Tarasiy","Taridin","Tatra",
               "Telec","Telerig","Tervel","TimE_r","TimE_reC_","TimE_rpA_lat","Tingiz","Tiradin","Tokhtaman",
               "Toktu","Tsog","Tsul","Tuk","Umor","Uturgur","Vakrim","Venda","Vetam","Vinekh","Yani","Yavantey",
               "YenC_epi","Yerneslu","YeC_tirek","Zabergan","Zenti","Tukiy","Aydar","Irkhan","Batir"],
               ["dynn_Vokil","dynn_Altsikur","dynn_Kashu","dynn_Barskhan","dynn_Barsil","dynn_Balanjar",
               "dynn_Vokil","dynn_Erdevulu","dynn_Silkid","dynn_Bilar","dynn_Sabir","dynn_Esegel","dynn_Izgil",
               "dynn_Askil","dynn_Bersula","dynn_Urazgilid","dynn_Kalmagorid","dynn_Klyuch","dynn_Uren_",
               "dynn_Mayna","dynn_Yasach","dynn_Utka","dynn_Bezd","dynn_Kurnal","dynn_Mesha","dynn_Kaban",
               "dynn_Oshnya","dynn_Tolkish","dynn_Izgar","dynn_Sulcha","dynn_Karmal"],
               father_name_chance = 0.0,
               grandfather_name_chance = 0.0,
              )
sabir = copy.deepcopy(bolghar); sabir.name = 'sabir'

tiele = Culture('tiele',
               ["C_ilbu","Aepak","Aibak","Alpra","Altunopa","Arbuz","Asalup","Asep","Atrak","Ayepa","BO_nek",
                "Bachman","Baytursun","Begluk","Beka","Blush","Bonyak","BorC_","Chemgura","Chilbuk","EldeC_yuk",
                "Ele","Eltut","Etrek","Girgen","Gzak","Gzi","Itlar","Ituk","Kemenche","Kitzes","KO_nC_ek","Kobyak",
                "Kolo","Kopti","Kopulch","Kotyan","Koza","Kozel","Kubasar","Kuntuvdi","Kutan","Kutesk","Kutlu",
                "Kza","Lavor","Manj","Menk","Otrok","Ovlur","Pulad","Saru","Sharaga","Sharukan","SevenC_","Seyhan",
                "Sicgan","SirC_an","Sokal","Sotan","Sugr","Suthoi","Tapar","Taz","Tetr","TO_rtogul","Togli",
                "Togortok","Toks","Tolun","Tugor","Vlur","Uzluk","Uzur","Zeyhan"],
               ["dynn_Hebixi","dynn_Irkin","dynn_Kobyakid","dynn_Qibi","dynn_Sijin","dynn_Wuhuan"],
               father_name_chance = 0.0,
               grandfather_name_chance = 0.0,
              )

romano_pannonian = Culture('romano_pannonian',
               ["E_dzhedzui","E_melleanui","E_mellui","E_tsui","Abucatui","Albinui","Albui","Allepsandri","Ambarui",
                "Ambroshui","Anaronacui","Anastashui","Andriai","An_erestui","An_echui","An_ui","Anton_inui","Anton_ui",
                "Aporon_ui","Arcadzui","Artapsiai","Archemnui","Achemnatui","Acheporecui","Augstui","Augstinui",
                "Aurelleanui","Aurellui","Auetui","Bartoromeui","Bashellui","Bellesariui","Ben_edeptui","Ben_acui",
                "Bechellui","Betumnatui","Buldzhui","Bran_odzhenui","Bren_ui","Bretan_ecui","Brezui","Che_chellui",
                "Che_llestinui","Che_sa","Camurodzhenui","Carinui","Carui","Cashui","Chershi","Ciaudzui","Ciementsui",
                "Cometai","Constan_i","Constantinui","Constantsui","Corn_ellui","Crasui","Cheprianui","Dadacui",
                "Dariui","Dechemui","Dechui","Dentupei","Desachentui","Decashui","Zhocllechanui","Zhodorui",
                "Zhon_eshui","Zhopui","Zhosporui","Domen_ecui","Domechanui","Dometsui","Drusui","Elpedzui",
                "En_odzui","Eposomnatui","Eubarnacui","Fabeanui","Fabiui","Fabrichui","Faustui","Felli","Flaueanui",
                "Floreanui","Dzhe_ui","Galleriui","Gallenui","Garui","Dzherashui","Dzhermanui","Dzhesatorecui",
                "Gordeanui","Gracui","Grachanui","Adrian","Eptapori","Ercullui","Onoriui","Emnatsui","Ellanui",
                "Ioan_i","Ioueanui","Esarnui","Iulleanui","Iullui","Iun_ui","Iustinui","Iuschen_eanui","Laurentsui",
                "Llo","Llontsui","Lleberiui","Llechen_ui","Luchui","Madacui","Magarui","Mamnui","Marchelinui",
                "Marcherui","Marcheanui","Marcomamnui","Marcui","Marinui","Mariui","Martinui","Mapsemeanui",
                "Mapseminui","Mapsemui","Mucapiui","N_epochanui","N_erua","Numereanui","Optaueanui","Optauiui",
                "Pascarui","Paulinui","Paurui","Petron_ui","Faranshi","Fellepui","Pompeiui","Ponchanui","Prescui",
                "Probui","Tolleme_ui","Publlui","Centui","Rascui","Resui","Romanui","Romurui","Rufinui","Rutsellui",
                "Saben_eanui","Satrei","Saturninui","Scherai","Samomnatui","Sandasatrui","Shempron_ui","Sheptsemiui",
                "Sherdzhui","Sheuerinui","Sheuerui","Shepstui","Sturanui","Shemmacui","Tachetui","Tarutsenui","Chuspai",
                "Chodoshui","Teberiui","Teredatsei","Chetsiui","Chetui","Tre_anui","Urbanui","Uallen_i",
                "Uallenchen_anui","Uallereanui","Ualleriui","Uardan_i","Uenantsui","Uespasheanui","Ueptro",
                "Ueptorinui","Uedzhellui","Uetalleanui","Uorusheanui"],
               ["dynn_Amandui","dynn_Bezo","dynn_CiE_uatui","dynn_CocheN_ui","dynn_DE_ntupeanui","dynn_Dracontsui",
                "dynn_Eullui","dynn_Flaueui","dynn_LlE_nturui","dynn_N_epoi","dynn_Marchea","dynn_Mellei",
                "dynn_Aullecara","dynn_PanoN_ui","dynn_Preuatui","dynn_Probeanui","dynn_Procullui","dynn_PompoN_ui",
                "dynn_Pochentsenui","dynn_Reparatui","dynn_Scordzescui","dynn_ShE_N_ellui","dynn_ShE_mproN_a",
                "dynn_ChE_nsoreui","dynn_ChE_rshei","dynn_Shero","dynn_Chechero","dynn_Shedzhenui","dynn_ScheraN_ui",
                "dynn_Ueator","dynn_UE_nusta","dynn_Ollebreui","dynn_UonoN_ei","dynn_Optaueanui","dynn_Dzhosoporeanui"],
               father_name_chance = 0.25,
               grandfather_name_chance = 0.3,
              )
romano_dacian = Culture('romano_dacian',
               ["Adreanu","Albinu","Alle_psandre_","Anastasiu","An_eciu","Anniu","Anton_u","Antun_inu","Arcagiu",
                "Aurellanu","Aurellu","Avetu","Beciellu","Be_llisariu","Bizu","Brasu","Brisu","Britannecu",
                "Bure_bastu","Carinu","Caru","Cassiu","Cie_ciellu","Cie_rsa","Cie_rsie","Ciesar","Cie_tripore",
                "Cintu","Claugiu","Clemenciu","Constand","Crassu","Cunstanciu","Cunstantinu","Curn_ellu","Dieciemu",
                "Dieciu","Die_ntope","Die_ntusucu","Die_sacie_ntu","Diesie_lme","Diesien_e","Diopu","Disape",
                "Diucletianu","Diusporu","Drusu","Dumeciu","Dumetianu","E_ciu","E_mallu","E_mellanu","E_nnogiu",
                "E_ptapore","E_ptapre_","E_ptare","E_pte_cie_ntu","E_ptiesucie","E_rcollu","E_spen_e","Fabeanu",
                "Fabiu","Faustu","Felleppu","Fellip","Flaveanu","Flureanu","Gaiu","Gallenu","Galleriu","Gallu",
                "Ge_diere","Ge_rmanu","Graccu","Gratianu","Gurdianu","Iuanne","Iullanu","Iullu","Iun_u","Iustien_anu",
                "Iustinu","Iuveanu","Llecien_u","Lleu","Llibieriu","Llonciu","Luciu","Mamnu","Mapsemeanu","Mapseminu",
                "Mapsemu","Marcianu","Marcie_llinu","Marcie_llu","Marcu","Marinu","Mariu","Martinu","Mucapiu","Mucapore",
                "N_e_putieanu","N_erva","Nume_reanu","Patron_u","Paullinu","Paulu","Pitru","Priscu","Probu","Publiu",
                "Pumpeiu","Puntianu","Rascu","Rascupore","Rascutormu","Resu","Romulu","Rufinu","Rumanu","Rutiellu",
                "Sabin_anu","Satre","Saturn_inu","Saucie","Scare","Scila","Sie_mpron_u","Siepiebe","Siepieru","Siepiru",
                "Sieporum","Sie_pstu","Sie_ptemiu","Sie_rgiu","Sie_verinu","Sie_veru","Sille","Simmacu","Sura","Tacietu",
                "Tarutinu","Tiebieriu","Tieciu","Tietu","Tiudosiu","Traianu","Unoriu","Uptaveanu","Uptaviu","Urbanu",
                "Vallend","Valle_ntin_anu","Valle_reanu","Valleriu","Vegellu","Venanciu","Veptur","Vepturinu",
                "Ve_spasieanu","Vitalleanu","Vulosiu"],
               ["dynn_AndroN_ecu","dynn_Atiellanu","dynn_AuspE_","dynn_BuciE_llariu","dynn_Capetullinu","dynn_Castcinu",
                "dynn_Catullinu","dynn_Clebanariu","dynn_Cucceiu","dynn_CutiesoN_u","dynn_Dacu","dynn_DiE_ciE_ballu",
                "dynn_Dulcieciu","dynn_Duratianu","dynn_GE_mE_llinu","dynn_GE_N_alle","dynn_AmmoN_u","dynn_OspE_",
                "dynn_LlimetaN_u","dynn_Udressanu","dynn_Urulleciu","dynn_Filupsenu","dynn_PrE_vientru",
                "dynn_Pulpudevanu","dynn_RE_spE_ptu","dynn_SarmesiE_getu","dynn_ScureloN_u","dynn_SiE_N_eciu",
                "dynn_SiemnefrE_","dynn_Taraboscie","dynn_Traciu","dynn_TuE_sianu","dynn_Olpiu","dynn_Veru",
                "dynn_VengiE_"],
               father_name_chance = 0.5,
               grandfather_name_chance = 0.5,
              )
romano_hispanic = Culture('romano_hispanic',
               ["Aemilianus","Aemilius","Aetius","Albinus","Alexander","Anastasius","Anicius","Annius","Antoninus",
                "Antonius","Arcadius","Aurelianus","Aurelius","Avitus","Belisarius","Britannicus","Caecilius",
                "Caesar","Carinus","Carus","Cassius","Claudius","Clementius","Constans","Constantinus","Constantius",
                "Cornelius","Crassus","Decimus","Decius","Diocletianus","Domitianus","Domitius","Drusus","Ennodius",
                "Fabianus","Fabius","Faustus","Felix","Flavianus","Florianus","Gaius","Galerius","Gallienus","Gallus",
                "Germanus","Gordianus","Gracchus","Gratianus","Hadrianus","Herculius","Honorius","Ioannes","Iovianus",
                "Iulianus","Iulius","Iulius-Caesar","Iunius","Iustinus","Iustinianus","Leo","Leontius","Liberius",
                "Licinius","Lucius","Magnus","Marcellinus","Marcellus","Marcianus","Marcus","Marinus","Marius",
                "Martinus","Maximianus","Maximinus","Maximus","Nepotianus","Nerva","Numerianus","Octavianus",
                "Octavius","Otho","Paulinus","Paulus","Petronius","Philippus","Pompeius","Pontianus","Priscus",
                "Probus","Publius","Quintus","Romanus","Romulus","Rufinus","Rutilius","Sabinianus","Saturninus",
                "Sempronius","Septimius","Sergius","Severinus","Severus","Sextus","Symmachus","Tacitus","Theodosius",
                "Tiberius","Titius","Titus","Traianus","Urbanus","Valens","Valentinianus","Valerianus","Valerius",
                "Venantius","Vespasianus","Victor","Victorinus","Vigilius","Vitalianus","Volusianus"],
               ["dynn_Acclenus","dynn_Agricolus","dynn_Albanius","dynn_Allius","dynn_Alpetius","dynn_Argentilius",
                "dynn_Bovecius","dynn_Caburius","dynn_Caesius","dynn_Cantius","dynn_Castricius","dynn_Cincius",
                "dynn_Corellius","dynn_Coronius","dynn_Curiatius","dynn_Cuspius","dynn_Duccius","dynn_Ferronius",
                "dynn_Flaminius","dynn_Flavius","dynn_Fuficius","dynn_Fullonius","dynn_Iustulenus","dynn_Laelius",
                "dynn_Larinius","dynn_Lucretius","dynn_Mamilius","dynn_Mancinius","dynn_Melvius","dynn_Memorius",
                "dynn_Meranius","dynn_Moschius","dynn_Naevidius","dynn_Nigrinius","dynn_Opimius","dynn_Papirius",
                "dynn_Pellieius","dynn_Petreius","dynn_Plancarius","dynn_Publicius","dynn_Pupius","dynn_Rantulanus",
                "dynn_Sapidius","dynn_Satullius","dynn_Sertorius","dynn_Sicinius","dynn_Statorius","dynn_Subrius",
                "dynn_Titulius","dynn_Tongius","dynn_Trebicius","dynn_Trebius","dynn_Tridius","dynn_Vagellius",
                "dynn_Vividius"],
               father_name_chance = 0.5,
               grandfather_name_chance = 0.5,
              )
sardinian = Culture('sardinian',
               ["Abisatu","AdA_mu","AdriA_nu","Alaverru","Albu","Alfonsu","AmbrO_su","Andria","Antiogu","AntO_ni",
                "Antoninu","Armannu","Arrammundu","Arzoccu","Ausone","Austinu","Austu","Baldu","Barisone","BartO_lu",
                "Basiliu","Bassu","Beneitu","Bernardu","Bobore","BonifA_tziu","Bosone","Carolu","Carule","CelestI_nu",
                "Clemente","Comita","CorrA_du","ConstantI_nu","Costantzu","Crabiele","Cristolu","Damianu","Danelu",
                "Dionisi","Dominigu","EusE_biu","Fabritziu","Felictu","Ferdinandu","Filipu","Franku","Frantziscu",
                "Furatu","Gabinu","GaetA_nu","Gaine","Gallu","Gasparru","Gavini","Gialetu","Giuanne","Giustinu",
                "Giustu","Goffredu","Gomita","GonA_riu","GO_samu","GosantI_nu","Grabielle","GrigO_riu","Guantine",
                "Gublenu","Gunnare","Idu","Iginu","Ignatziu","Ilariu","IstE_vene","Izocor","Jacopu","Jagu","Juanne",
                "Justu","Kiprianu","Laurentu","Leonardu","Leone","Lircu","Lissandru","Luca","Luciu","Lussurgiu",
                "Manfredu","Markellu","Marku","Marianu","Martinu","Mattia","Matteu","Mauru","Micheli","Migali",
                "Mighele","Mikelli","Nicolau","Nigola","Onoradu","Orgodor","Orizone","Orlandu","Orzocor",
                "Pancratziu","Pantaleu","Pascale","Patriziu","PA_ulu","Pedru","Pellegrinu","Pirillu","Pizente",
                "Ponzu","Prosperu","Ramundu","Robertu","Sadurru","Salluri","Saltaru","SalU_siu","Samaritanu",
                "SamuE_li","Saraginu","Sebustianu","Serafinu","SE_rgiu","Simachu","Simione","Simplitziu","Siru",
                "Sparau","TA_ntalu","Tedore","Tedu","Tobias","Tocode","Tommasu","TorbE_nu","Torchitor",
                "Torchitoriu","Ubertu","Ugone","Ugu","Vissente","Vittore","Vivianu","Zennaru","ZirO_nimu",
                "Zonetu","Zuseppe"],
               ["dynn_Floris","dynn_Gambella","dynn_Manca","dynn_Melis","dynn_Meloni","dynn_Mura","dynn_Pinna",
                "dynn_Piras","dynn_Porcu","dynn_Salusiu_de_Lacon","dynn_Sanna","dynn_Serra","dynn_Spanu",
                "dynn_Torchitorio","dynn_Usai"],
               father_name_chance = 0.25,
               grandfather_name_chance = 0.3,
              )
romano_illyrian = Culture('romano_illyrian',
               ["Aemilianus","Aemilius","Aetius","Albinus","Alexander","Anastasius","Anicius","Annius",
               "Antoninus","Antonius","Arcadius","Aurelianus","Aurelius","Avitus","Belisarius",
               "Britannicus","Caecilius","Caesar","Carinus","Carus","Cassius","Claudius","Clementius",
               "Constans","Constantinus","Constantius","Cornelius","Crassus","Decimus","Decius",
               "Diocletianus","Domitianus","Domitius","Drusus","Ennodius","Fabianus","Fabius",
               "Faustus","Felix","Flavianus","Florianus","Gaius","Galerius","Gallienus","Gallus",
               "Germanus","Gordianus","Gracchus","Gratianus","Hadrianus","Herculius","Honorius",
               "Ioannes","Iovianus","Iulianus","Iulius","Iulius-Caesar","Iunius","Iustinus",
               "Iustinianus","Leo","Leontius","Liberius","Licinius","Lucius","Magnus","Marcellinus",
               "Marcellus","Marcianus","Marcus","Marinus","Marius","Martinus","Maximianus",
               "Maximinus","Maximus","Nepotianus","Nerva","Numerianus","Octavianus","Octavius",
               "Otho","Paulinus","Paulus","Petronius","Philippus","Pompeius","Pontianus","Priscus",
               "Probus","Publius","Quintus","Romanus","Romulus","Rufinus","Rutilius","Sabinianus",
               "Saturninus","Sempronius","Septimius","Sergius","Severinus","Severus","Sextus",
               "Symmachus","Tacitus","Theodosius","Tiberius","Titius","Titus","Traianus","Urbanus",
               "Valens","Valentinianus","Valerianus","Valerius","Venantius","Vespasianus","Victor",
               "Victorinus","Vigilius","Vitalianus","Volusianus"],
               ["dynn_Aebutius","dynn_Aeronius","dynn_Ancharenus","dynn_Aprofennius","dynn_Artorius",
               "dynn_Axenna","dynn_Baebidius","dynn_Barbaricius","dynn_Billianius","dynn_Buzetius",
               "dynn_Camusenus","dynn_Constantinus","dynn_Crispuleius","dynn_Dirutius",
               "dynn_Eupunius","dynn_Feredius","dynn_Flavius","dynn_Florius","dynn_Garinius",
               "dynn_Ligustius","dynn_Mescenius","dynn_Murcidius","dynn_Nerfinius",
               "dynn_Obultronius","dynn_Palpellius","dynn_Quesidius","dynn_Saufeius",
               "dynn_Subulnius","dynn_Tarconius","dynn_Tarius","dynn_Tatusius","dynn_Titusidius",
               "dynn_Tloantius","dynn_Urgulanius","dynn_Utius","dynn_Varenus","dynn_Veiedius",
               "dynn_Vesidius"],
               father_name_chance = 0.50,
               grandfather_name_chance = 0.50,
              )

carpodaci = Culture('carpodaci',
               ["Avizina","Bastiza","Blegissa","Bikili","Burebista","Bryzos","Byzo","Comosicus","Cotiso","Dablosa",
                "Dadas","Dadazi","Daizus","Damanais","Dapyx","Denzibalos","Dekinais","Dentupes","Dentusucu","Deopus",
                "Deospor","Desakenthos","Diazelmis","Diazenis","Dicomes","Dieri","Dizapes","Dhegh","Dourpokis","Dotos",
                "Dotouzi","Drilgisa","Eptaikenthos","Eptaper","Eptaporis","Heptaporis","Eptarys","Eptesuchis","Ezbenis",
                "Gaidres","Kaigiza","Komakiza","Kerses","Kerza","Ketriporis","Komozoi","Mucapor","Mukaboris","Mukapius",
                "Natopor","Oroles","Petipor","Pouridour","Pytros","Rhaskos","Rhaskuporis","Rheskutorm","Rhesos",
                "Rolouzis","Satres","Sautes","Skaris","Scorylo","Skilas","Sura","Taruthin","Tarutinos","Thiamar",
                "Tsinna","Zebeleizis","Zile","Zipaibes","Ziper","Zipuronn","Zipyros"],
               ["dynn_Rhaskuporis","dynn_Blegissa","dynn_Burebista","dynn_Dadazi","dynn_Denzibalos","dynn_Dotouzi",
                "dynn_Kerses","dynn_Ketriporis","dynn_Heptaporis","dynn_Rhaskuporis","dynn_Zipyros"],
               father_name_chance = 0.5,
               grandfather_name_chance = 0.5,
              )
illyrian = Culture('illyrian',
               ["Bikili","Brasus","Burebista","Bryzos","Byzo","Dentupes","Dentusucu","Deopus","Deospor",
               "Desakenthos","Diazelmis","Diazenis","Dizapes","Eptaikenthos","Eptaper","Eptaporis",
               "Heptaporis","Eptarys","Eptesuchis","Ezbenis","Gaidres","Kerses","Kerza","Ketriporis",
               "Mukaboris","Mukapius","Pytros","Rhaskos","Rhaskuporis","Rheskutorm","Rhesos","Satres",
               "Sautes","Skaris","Skilas","Sura","Taruthin","Tarutinos","Zile","Zipaibes","Ziper",
               "Zipuronn","Zipyros"],
               ["dynn_Brasus","dynn_Desakenthos","dynn_Eptaikenthos","dynn_Ezbenis","dynn_Kerza",
               "dynn_Kerses","dynn_Ketriporis","dynn_Heptaporis","dynn_Rhaskuporis","dynn_Zipyros"],
               father_name_chance = 0.5,
               grandfather_name_chance = 0.5,
              )

vistula_veneti = Culture('vistula_veneti',
               ["Algirdas","Antanas","Antavas","Aras","Arunas","Azuolas","Budrys","Bukantas","Butavas","Butigeidis",
                "Butvydas","Daugvilas","Daumantas","Dausprungas","Dravenis","Erdenis","Erdvilas","Gedigaudas",
                "Gediminas","Gedivilas","Gintaras","Gintautas","Girdenis","Irmantas","Jaunutis","Jogaila","Jovirdas",
                "Kantibutas","Karijotas","Kesgaila","Kestutis","Korigaila","Korybutas","Lasukas","Lingvenis","Liudas",
                "Lubartas","Lutuveras","Merkelis","Mindaugas","Minigaila","Mantvydas","Movkoldas","Narimantas",
                "Povilas","Pukuveras","Rimantas","Rimgaila","Rimvydas","Ringaudas","Sarunas","Skirgaila",
                "Songaila","Svarnas","Svitrigaila","Tarvydas","Tovtivilas","Traidenis","Treniotas","Vainius",
                "Vaisvilkas","Valimantas","Vidmantas","Vingoldas","Virmantas","Visvaldis","Vizgirdas","Vykintas",
                "Vytautas","Vytenis","Zivinbudas","Zygimantas"],
               ["dynn_Ulinniks","dynn_Ringaudas","dynn_Dausprungas","dynn_Karijotas","dynn_Lasukas","dynn_Liudas",
               "dynn_Lubartas","dynn_Merkelis","dynn_Rimvydas","dynn_Vizgirdas"],
               father_name_chance = 0.0,
               grandfather_name_chance = 0.0,
              )
east_galindian = copy.deepcopy(vistula_veneti); east_galindian.name = 'east_galindian'
galindian = Culture('galindian',
               ["Alvydas","Arelis","Auctune","Bajoras","Beidras","Budo","Dagonis","Ekkelis","Galindas",
                "Gauronas","Gerdautas","Glande","Golding","Jauguttis","Karatas","Klukis","Kugis",
                "Milzas","Nomedas","Prusas","Sergonis","Ulinniks","Ulitis"],
               ["dynn_Liudas","dynn_Ringaudas","dynn_Antavas","dynn_Azuolas","dynn_Daugvilas",
                "dynn_Gedivilas","dynn_Lutuveras","dynn_Mantvydas","dynn_Pukuveras","dynn_Vidmantas"],
               father_name_chance = 0.0,
               grandfather_name_chance = 0.0,
              )
prussian = copy.deepcopy(galindian); prussian.name = 'prussian'
sudovian = copy.deepcopy(galindian); sudovian.name = 'sudovian'
aesti = Culture('aesti',
               ["Algirdas","Antanas","Antavas","Aras","Arunas","Azuolas","Budrys","Bukantas","Butavas",
                "Butigeidis","Butvydas","Daugvilas","Daumantas","Dausprungas","Dravenis","Erdenis",
                "Erdvilas","Gedigaudas","Gediminas","Gedivilas","Gintaras","Gintautas","Girdenis",
                "Irmantas","Jaunutis","Jogaila","Jovirdas","Kantibutas","Karijotas","Kesgaila",
                "Kestutis","Korigaila","Korybutas","Lasukas","Lingvenis","Liudas","Lubartas",
                "Lutuveras","Merkelis","Mindaugas","Minigaila","Mantvydas","Movkoldas","Narimantas",
                "Povilas","Pukuveras","Rimantas","Rimgaila","Rimvydas","Ringaudas","Sarunas",
                "Skirgaila","Songaila","Svarnas","Svitrigaila","Tarvydas","Tovtivilas","Traidenis",
                "Treniotas","Vainius","Vaisvilkas","Valimantas","Vidmantas","Vingoldas","Virmantas",
                "Visvaldis","Vizgirdas","Vykintas","Vytautas","Vytenis","Zivinbudas","Zygimantas"],
               ["dynn_Ulinniks","dynn_Ringaudas","dynn_Dausprungas","dynn_Karijotas","dynn_Lasukas",
                "dynn_Liudas","dynn_Lubartas","dynn_Merkelis","dynn_Rimvydas","dynn_Vizgirdas"],
               father_name_chance = 0.0,
               grandfather_name_chance = 0.0,
              )

old_slavic = Culture('old_slavic',
               ["Boris","Boz","Bryachislav","Vladimir","Vladislav","Volodar","Vsevolod","Vseslav","Vysheslav",
                "Vyacheslav","Izyaslav","Mstislav","Pozvizd","Rodoslav","Rostislav","Svyatopolk","Svyatoslav",
                "Premysl","Radigost","Radimir","Yaromir","Stanislav","Sudislav","Gradimir","Gremislav","Gradislav",
                "Yaropolk","Yaroslav","Velislav","Godogost","Gostevid","Gostomysl","Gorazd","Godobrat","Godoslav",
                "Vyshemir","Tatimir","Tverdimir","Tverdislav","Chaslav","Sobeslav","Rogovlad","Rosslav","Vsegrad",
                "Vsemil","Vsemysl","Venceslav","Mechislav","Miloduh","Osmomysl","Ostromir","Veselin","Zdebor",
                "Mstivoj","Mojmir","Ladislav","Miroslav","Veslav","Kreslav","Klonimir","Bajen","Vidogost","Ludevit",
                "Lutogost","Domoslav","Dragomir","Vlastimir","Voeneg","Voislav","Vitigost","Volibor","Vitomir",
                "Vladduh","Beloslav","Berimir","Berislav","Blagoslav","Boleslav","Borimir","Vadim","Vatslav",
                "Velerad","Velimir"],
               ["dynn_Antya-Inda","dynn_Boris","dynn_Domoslavid","dynn_Domovich","dynn_Godogost","dynn_Ognjen",
                "dynn_Ostromir","dynn_Solowhoff","dynn_Stanysl","dynn_Venedi","dynn_Volivch","dynn_Vsegrad"],
               father_name_chance = 0.1,
               grandfather_name_chance = 0.4,
              )

przeworsk = Culture('przeworsk',
               ["Apano","Arantonio","Arco","Cabruno","Camalo","Ciliua","Eburus","Labaecus","Lancius","Maelo","Pisiri",
                "Pucio","Taio","Talabus","Tanginus"],
               ["dynn_Vernogenos","dynn_Arantonio","dynn_Cabruno","dynn_Eburus","dynn_Labaecus","dynn_Pisiri",
                "dynn_Talabus","dynn_Tanginus"],
               father_name_chance = 0.25,
               grandfather_name_chance = 0.3,
              )
denziner = Culture('denziner',
               ["Adalfuns","Adalrik","Alarik","Alhreiks","Alhwaharyis","Alrek","Amalareiks","Andagis",
                "Angantyr","Ansila","Arareiks","Ardarik","Ardiarik","Aspar","Athalagild","Athalareiks",
                "Athalarik","Athalok","Athanagild","Athanareiks","Athanarik","Audoaker","Auswinthus",
                "Avagis","Badwila","Beremud","Berig","Botheric","Childefonsus","Chindaswintha","Dag",
                "Ediulf","Egika","Eirik","Elemund","Ermanarik","Ermingeld","Eurik","Eutharik","Evermud",
                "Evorik","Fridarik","Frideger","Frithigern","Geberik","Giselrik","Gizur","Gunderik",
                "Haduswinth","Hairuwulf","Harfidel","Hathus","Hermanarik","Hermanagild","Hildefons",
                "Hunvil","Ildefons","Kindaswinth","Kunimund","Leovigild","Liuva","Rekimir","Rikimar",
                "Roderik","Sigerik","Sigibert","Swinthila","Tautila","Theodahad","Theodemir","Theoderik",
                "Thiudafred","Thiudareiks","Thurisind","Thurismud","Thurismund","Thuruar","Thurisvinthus",
                "Tius","Ulfilas","Veremund","Veterik","Ulfila","Wingurik"],
               ["dynn_Alhwaharying","dynn_Beriging","dynn_Haduswinthing","dynn_Thurismuding"],
               father_name_chance = 0.0,
               grandfather_name_chance = 0.8,
              )
vidivarii = Culture('vidivarii',
               ["Alvydas","Arelis","Auctune","Bajoras","Beidras","Budo","Dagonis","Ekkelis","Galindas","Gauronas",
               "Gerdautas","Glande","Golding","Jauguttis","Karatas","Klukis","Kugis","Milzas","Nomedas","Prusas",
               "Sergonis","Ulinniks","Ulitis","Adalfuns","Adalrik","Alarik","Alhreiks","Alhwaharyis","Alrek",
               "Amalareiks","Andagis","Angantyr","Ansila","Arareiks","Ardarik","Ardiarik","Aspar","Athalagild",
               "Athalareiks","Athalarik","Athalok","Athanagild","Athanareiks","Athanarik","Audoaker","Auswinthus",
               "Avagis","Badwila","Beremud","Berig","Botheric","Childefonsus","Chindaswintha","Dag","Ediulf","Egika",
               "Eirik","Elemund","Ermanarik","Ermingeld","Eurik","Eutharik","Evermud","Evorik","Fridarik","Frideger",
               "Frithigern","Geberik","Giselrik","Gizur","Gunderik","Haduswinth","Hairuwulf","Harfidel","Hathus",
               "Hermanarik","Hermanagild","Hildefons","Hunvil","Ildefons","Kindaswinth","Kunimund","Leovigild",
               "Liuva","Rekimir","Rikimar","Roderik","Sigerik","Sigibert","Swinthila","Tautila","Theodahad",
               "Theodemir","Theoderik","Thiudafred","Thiudareiks","Thurisind","Thurismud","Thurismund","Thuruar",
               "Thurisvinthus","Tius","Ulfilas","Veremund","Veterik","Ulfila","Wingurik"],
               ["dynn_Arelistaws","dynn_Childefontaws","dynn_Dagtaws","dynn_Roderiktaws","dynn_Sigiberttaws",
                "dynn_Thiuderiktaws","dynn_Ulfilataws"],
               father_name_chance = 0.0,
               grandfather_name_chance = 0.8,
              )
gustow = Culture('gustow',
               ["Adalfuns","Adalrik","Alarik","Alhreiks","Alhwaharyis","Alrek","Amalareiks","Andagis",
                "Angantyr","Ansila","Arareiks","Ardarik","Ardiarik","Aspar","Athalagild","Athalareiks",
                "Athalarik","Athalok","Athanagild","Athanareiks","Athanarik","Audoaker","Auswinthus",
                "Avagis","Badwila","Beremud","Berig","Botheric","Childefonsus","Chindaswintha","Dag",
                "Ediulf","Egika","Eirik","Elemund","Ermanarik","Ermingeld","Eurik","Eutharik","Evermud",
                "Evorik","Fridarik","Frideger","Frithigern","Geberik","Giselrik","Gizur","Gunderik",
                "Haduswinth","Hairuwulf","Harfidel","Hathus","Hermanarik","Hermanagild","Hildefons",
                "Hunvil","Ildefons","Kindaswinth","Kunimund","Leovigild","Liuva","Rekimir","Rikimar",
                "Roderik","Sigerik","Sigibert","Swinthila","Tautila","Theodahad","Theodemir","Theoderik",
                "Thiudafred","Thiudareiks","Thurisind","Thurismud","Thurismund","Thuruar","Thurisvinthus",
                "Tius","Ulfilas","Veremund","Veterik","Ulfila","Wingurik"],
               ["dynn_Adalfunsing","dynn_Chindaswinthing","dynn_Daging","dynn_Giselriking",
               "dynn_Hunviling","dynn_Ildefonsing","dynn_Swinthiling"],
               father_name_chance = 0.0,
               grandfather_name_chance = 0.8,
              )
warnic = Culture('warnic',
               ["Aage","Asmus","Bendix","BO_rries","Dankert","Eggert","Eide","Eike","Eimer","Fedder",
                "Fiete","LU_bbe","LU_deke","Jorin","LU_der","Meinert","Paschen","Reik","Sievert",
                "SO_nke","Tanger","Tiele","Tjaden","TO_lke","Wiggert"],
               ["dynn_Aauolfing","dynn_Lьding","dynn_Eimering","dynn_Wiggerting",
               "dynn_Paschening","dynn_Meinerting","dynn_Jorining","dynn_Sieverting"],
               father_name_chance = 0.0,
               grandfather_name_chance = 0.0,
              )
lebus = Culture('lebus',
               ["Adalfuns","Adalrik","Alarik","Alhreiks","Alhwaharyis","Alrek","Amalareiks","Andagis",
                "Angantyr","Ansila","Arareiks","Ardarik","Ardiarik","Aspar","Athalagild","Athalareiks",
                "Athalarik","Athalok","Athanagild","Athanareiks","Athanarik","Audoaker","Auswinthus",
                "Avagis","Badwila","Beremud","Berig","Botheric","Childefonsus","Chindaswintha","Dag",
                "Ediulf","Egika","Eirik","Elemund","Ermanarik","Ermingeld","Eurik","Eutharik","Evermud",
                "Evorik","Fridarik","Frideger","Frithigern","Geberik","Giselrik","Gizur","Gunderik",
                "Haduswinth","Hairuwulf","Harfidel","Hathus","Hermanarik","Hermanagild","Hildefons",
                "Hunvil","Ildefons","Kindaswinth","Kunimund","Leovigild","Liuva","Rekimir","Rikimar",
                "Roderik","Sigerik","Sigibert","Swinthila","Tautila","Theodahad","Theodemir",
                "Theoderik","Thiudafred","Thiudareiks","Thurisind","Thurismud","Thurismund","Thuruar",
                "Thurisvinthus","Tius","Ulfilas","Veremund","Veterik","Ulfila","Wingurik"],
               ["dynn_Ediulf","dynn_Ediulf","dynn_Harfidel","dynn_Thiudareiks",
               "dynn_Hildefons"],
               father_name_chance = 0.0,
               grandfather_name_chance = 0.8,
              )
old_saxon = Culture('old_saxon',
               ["Abo","Aelle","Banzleib","Berthoala","Berthoald","Bertold","Boddic","Bodicus","Cissa",
                "Cymen","Dietrich","Eberhard","Ethelhard","Freawine","Frithuwald","Gelder","Guictglis",
                "Hadugato","Harthgate","Harthwigate","Hattugatus","Hengest","Hulderic","Liudolf",
                "Marbold","Siegehard","Sigward","Swarticke","Theoderic","Virich","Walpert","Warin",
                "Warinechin","Wecta","Wernicke","Weybrecht","Widukind","Wigebert","Willichin","Withgils",
                "Witikind","Witta","Wlencing"],
               ["dynn_A_lling","dynn_Abing","dynn_Aelling","dynn_Berding","dynn_Bethoalding",
                "dynn_Billung","dynn_Cerdicing","dynn_Freawining","dynn_Geldering","dynn_Gelding",
                "dynn_Gesecging","dynn_Hadugating","dynn_Hattonid","dynn_Huldericing","dynn_Maqui-Coline",
                "dynn_Marbolding","dynn_Myrgings","dynn_Ordulring","dynn_Otting","dynn_Theodring",
                "dynn_UhtrA_ding","dynn_Viriching","dynn_Viriching","dynn_Weybrechting","dynn_Widuking",
                "dynn_Wigeberting","dynn_Wistas","dynn_Withgilsing","dynn_Wlencing","dynn_Wuffingas"],
               father_name_chance = 0.0,
               grandfather_name_chance = 0.8,
              )
dane = Culture('dane',
               ["Anundr","Arnfast","A_li","A_lfr","A_lfgeir","AndrE_s","ArnbjO_rn","ArngrI_mr","A_rni",
                "A_sbjO_rn","A__ke","A_skell","Baldr","Bersi","BjO_rn","Bragi","BuT_li","BA_rD_r",
                "Birgir","BU_i","BO_D_var","BO_tO_lfr","BrynjO_lfr","BergT_O_r","Dan","Dagr","DY_ri",
                "Egill","Einarr","EilI_fr","Emundr","EirI_kr","Eysteinn","Einar","Freyr","Fasti",
                "FriT_rI_kr","FrIrekr","FrO_T_i","FO_lki","Flosi","Geirr","GuT_mundr","GuT_rO_T_r",
                "Gunnarr","GandA_lfr","GnU_pa","Gormr","GrI_mr","GuT_frI_T_r","Grettir","Haraldr",
                "Haukr","Helgi","Hrafn","HA__kon","Hallsteinn","Hemingr","HO_lmgeirr","HrO_lfr",
                "Hrani","HA_steinn","HjA_lmar","HrO_T_geirr","HrO_D_O_lfr","HrE_rekr","HY_singr",
                "HalfdA_n","HerjO_lfr","HO_rD_r","HO_gni","HU_nT_jO_fr","Hordaknutr","IngO_lfr",
                "Ingimar","Ingjaldr","I_var","JA_tvarD_r","JO_rundr","Karl","Kjartan","KolbjO_rn",
                "Ketill","Ketilmundr","KnU_tr","Kollr","KA_ri","Kolbeinn","LjO_tr","MagnU_s",
                "NjA_ll","Oddr","Ormr","O_rvar","O_nundr","O_feigr","O_lafr","O_ttar","O_lvir",
                "O_gmundr","Refr","Ragnarr","RO_gnvaldr","Refill","RI_kU_lfr","Snorri","SigurT_r",
                "StarkaT_r","Steinn","Sturla","StyrbjO_rn","SumarliT_i","Suni","Sveinn","Sverker",
                "SE_mundr","SO_lvi","SkU_li","SigrbjO_rn","Sigtryggr","StyrkA_r","SO_rkvir",
                "SkarphE_D_inn","SkjO_ldr","Tolir","T_orbjO_rn","T_orbrandr","T_orsteinn","Tyke",
                "T_iO_D_mundr","TO_ki","T_orfinnr","T_orD_r","T_orgils","T_O_rO_lfr","TO_sti",
                "T_jO_stO_lfr","Tryggvi","U_lfr","U_lfhE_D_inn","U_lfkell","Vagn","VE_mundr",
                "Valdemar","VigfU_s","ValT_jO_fr","Yngvar"],
               ["dynn_Daning","dynn_FrO_D_ing","dynn_Danping","dynn_Mikillati","dynn_Halfding",
                "dynn_Hrothging","dynn_Halging","dynn_HrO_lfring","dynn_Kraking","dynn_Olofing",
                "dynn_Gyrding","dynn_Sigtrygging"],
               father_name_chance = 0.0,
               grandfather_name_chance = 0.8,
              )

gothic = Culture('gothic',
               ["Ablabius","Achila","Agila","Agiwulf","Agriwulf","Aidoingus","Aithanarid","Alaric","Alatheus","Alaviv",
                "Alica","Aligern","Alla","Amal","Amalaric","Ammius","Anagastes","Andagis","Anianus","Ansila","Ansis",
                "Aoric","Apahida","Ardabur","Ardaric","Argaith","Ariaric","Arimir","Arius","Arnegisclus","Arvandus",
                "Asbad","Aspar","Ataulf","Ataulph","Athalaric","Athanagild","Athanaric","Atharid","Athaulf","Babai",
                "Badua","Baduila","Baza","Berig","Berimud","Berimund","Bessa","Bessas","Bessi","Beuca","Beucad",
                "Bigelis","Bilimer","Borani","Braga","Brandila","Candac","Cannabas","Cannabaudes","Cethegus",
                "Chindasuinth","Cniva","Cnivida","Colias","Crocus","Cunigast","Cunimund","Cyrila","Dubius","Duda",
                "Ebermud","Eberwolf","Ebrimud","Edica","Eraric","Eriulf","Ermanaric","Ermelandus","Ervig","Euric",
                "Eutharic","Farnobius","Fastida","Feletheus","Feva","Filimer","Flaccitheus","Fravitta","Fredegar",
                "Fretela","Frideric","Fridigern","Frigeridus","Frithila","Fritigern","Gadaric","Gainas","Gaiseric",
                "Galindo","Galindus","Gaut","Gauterit","Geberic","Gelimer","Gento","Gerung","Gesalec","Gesimund",
                "Getica","Goar","Goddas","Godegisel","Godigisclus","Goiaricus","Gouththas","Gundehar","Gundiok",
                "Gundobad","Gunteric","Gunthigis","Gutthikas","Hadubrand","Heldebald","Heldefredus","Heribrand",
                "Hermangild","Hermenigild","Herminafrid","Hernegliscus","Hildebad","Hildebrand","Hilderic",
                "Hilderith","Himnerith","Hisarna","Hulmul","Huml","Huneric","Hunigild","Hunimund","Hunulf",
                "Hunumund","Ibba","Ildebad","Inna","Irnfried","Jordanes","Lagariman","Lampridius","Leovigild",
                "Leuvibild","Livila","Marcomir","Modaharius","Modares","Munderic","Mundo","Namatius","Naulabates",
                "Nidada","Niketas","Odoin","Odotheus","Odovacar","Ostrogotha","Osuin","Ovida","Patza","Radagaisus",
                "Rausimod","Recared","Reccared","Recceswinth","Rechiar","Rechimund","Recitach","Rekitach","Remismund",
                "Respa","Retemeri","Rhima","Ricimer","Rictiovarus","Rikiar","Roderic","Sueridus","Sunnias","Thrasamund",
                "Thrasaric","Thraustila","Totila","Tribigild","Tufa","Tuluin","Ulfilas","Unigild","Unila","Unimund",
                "Uraias","Valamer","Valamir","Valaravans","Valia","Vandalarius","Vandil","Veduco","Vetericus",
                "Vetranio","Videric","Vidigoia","Vidimir","Viliaris","Vinitharius","Visimar","Vithimiris","Vithmiris",
                "Vitigis","Vittamar","Vultuulf","Wala","Walahmar","Wallia","Wamba","Wella","Winguric","Witige","Wittigis"],
               ["dynn_Ardabur","dynn_Crimling","dynn_Zuzusing","dynn_Aithanariding","dynn_Chindasuinth",
                "dynn_Hadubranding","dynn_Fridigerning"],
               father_name_chance = 0.1,
               grandfather_name_chance = 0.5,
              )
wielbark = copy.deepcopy(gothic); wielbark.name = 'wielbark'

alan = Culture('alan',
               ["E_lbeg","E_mbalan","Aghsartan","Alatey","Akhsar","Anbal","Anbazuk","Aravat","Arsen","Askhkadar",
                "Ashot","Aslan","Aspar","Athom","Balambar","Balsag","Barlah","BE_qE_tar","Basil","Bazuk","Beler",
                "Ber","BirE_g","Boz-Uruz","BuU_rgur","Buriberdi","Burikhan","Candak","Chelakhsartag","Davit",
                "Djadaron","Durgulel","DzE_rE_s","GE_tE_g","Georgy","Girgon","Gokhar","Gubaz","Guram","Hasqar",
                "Huddan","Istor","Itaz","Iveri","Kandak","Kandz","Kavtia","Kaur","Khankhusy","KhE_tag","Konstantin",
                "Kubal","Kuddana","Kul","Kuluk","Lak","Levan","Pulad","Respendial","Rosmag","Safrak","Sakhir",
                "Sangipan","Saros","Sathis","Savkudz","Soslan","Suarn","Syrdon","Taymuraz","Taus","Totraz","Urdure",
                "Uruzma","Uturku","Yasynya","Zaur"],
               ["dynn_ArdasentA_","dynn_GA_bA_ratA_","dynn_DzA_rA_hohtA_","dynn_DzebysatA_","dynn_DjerdjitA_",
                "dynn_GuyrdzybetA_","dynn_ZA_ndjiatA_","dynn_KA_rkuystA_","dynn_DjykkajtA_","dynn_GodjysatA_",
                "dynn_PA_rrA_statA_","dynn_HetA_gkatA_","dynn_HA_darcatA_","dynn_TuallA_gtA_","dynn_FA_rniatA_",
                "dynn_Ephraimid","dynn_TandelatA_","dynn_TsA_ykostA_","dynn_SozanatA_","dynn_MA_rzojtA_","dynn_Ovsia"],
               father_name_chance = 0.0,
               grandfather_name_chance = 0.0,
              )
western_alan = copy.deepcopy(alan); western_alan.name = 'western_alan'

culture_list = {'test_roman':test_roman,
                'sami':sami,
                'khanty':khanty,
                'komi':komi,
                'fenni':fenni,
                'merya':merya,
                'muroma':muroma,
                'meshchera':meshchera,
                'mari':mari,
                'mordvin':mordvin,
                'mogyer':mogyer,
                'gorkhovo':gorkhovo,
                'sargat':sargat,
                'khanty':khanty,
                'samoyed':samoyed,
                'yeniseian':yeniseian,
                'tungusic':tungusic,
                'suebi':suebi,
                'langobard':langobard,
                'hunnic':hunnic,
                'khuni':khuni,
                'bolghar':bolghar,
                'sabir':sabir,
                'tiele':tiele,
                'romano_pannonian':romano_pannonian,
                'romano_hispanic':romano_hispanic,
                'romano_dacian':romano_dacian,
                'sardinian':sardinian,
                'romano_illyrian':romano_illyrian,
                'carpodaci':carpodaci,
                'illyrian':illyrian,
                'vistula_veneti':vistula_veneti,
                'east_galindian':east_galindian,
                'galindian':galindian,
                'sudovian':sudovian,
                'prussian':prussian,
                'aesti':aesti,
                'old_slavic':old_slavic,
                'przeworsk':przeworsk,
                'denziner':denziner,
                'vidivarii':vidivarii,
                'gustow':gustow,
                'warnic':warnic,
                'lebus':lebus,
                'old_saxon':old_saxon,
                'dane':dane,
                'gothic':gothic,
                'wielbark':wielbark,
                'alan':alan,
                'western_alan':western_alan,
                'norse':norse}
