name = "When the World Stopped Making Sense"
tags={
	"Bookmarks"
	"Culture"
	"Events"
	"Gameplay"
	"Historical"
	"Map"
	"Religion"
	"Total Conversion"
}
version = "0.1.8"
supported_version="1.16.*"
path = "mod/WtWSMS"
replace_path="history/characters"
replace_path="history/cultures"
replace_path="history/provinces"
replace_path="history/titles"
picture="thumbnail.png"
remote_file_id="2858562094"