#!/bin/bash

echo "ballista";find . -iname "*.yml" -exec sed -i -b "s/^ ballista/ #ballista/g" {} +
echo "ballista_flavor";find . -iname "*.yml" -exec sed -i -b "s/^ ballista_flavor/ #ballista_flavor/g" {} +
echo "name_list_korean";find . -iname "*.yml" -exec sed -i -b "s/^ name_list_korean/ #name_list_korean/g" {} +
echo "name_list_ryukyuan";find . -iname "*.yml" -exec sed -i -b "s/^ name_list_ryukyuan/ #name_list_ryukyuan/g" {} +
echo "name_list_vietnamese";find . -iname "*.yml" -exec sed -i -b "s/^ name_list_vietnamese/ #name_list_vietnamese/g" {} +
echo "name_list_romansh";find . -iname "*.yml" -exec sed -i -b "s/^ name_list_romansh/ #name_list_romansh/g" {} +
echo "japanese";find . -iname "*.yml" -exec sed -i -b "s/^ japanese/ #japanese/g" {} +
echo "japanese_collective_noun";find . -iname "*.yml" -exec sed -i -b "s/^ japanese_collective_noun/ #japanese_collective_noun/g" {} +
echo "japanese_prefix";find . -iname "*.yml" -exec sed -i -b "s/^ japanese_prefix/ #japanese_prefix/g" {} +
echo "ryukyuan";find . -iname "*.yml" -exec sed -i -b "s/^ ryukyuan/ #ryukyuan/g" {} +
echo "ryukyuan_collective_noun";find . -iname "*.yml" -exec sed -i -b "s/^ ryukyuan_collective_noun/ #ryukyuan_collective_noun/g" {} +
echo "ryukyuan_prefix";find . -iname "*.yml" -exec sed -i -b "s/^ ryukyuan_prefix/ #ryukyuan_prefix/g" {} +
echo "king_male_tangut";find . -iname "*.yml" -exec sed -i -b "s/^ king_male_tangut/ #king_male_tangut/g" {} +
echo "dynn_Abu";find . -iname "*.yml" -exec sed -i -b "s/^ dynn_Abu/ #dynn_Abu/g" {} +
echo "dynn_Suzuki";find . -iname "*.yml" -exec sed -i -b "s/^ dynn_Suzuki/ #dynn_Suzuki/g" {} +
echo "dynn_Tanaka";find . -iname "*.yml" -exec sed -i -b "s/^ dynn_Tanaka/ #dynn_Tanaka/g" {} +
echo "dynn_Park";find . -iname "*.yml" -exec sed -i -b "s/^ dynn_Park/ #dynn_Park/g" {} +
echo "dynn_Soma";find . -iname "*.yml" -exec sed -i -b "s/^ dynn_Soma/ #dynn_Soma/g" {} +
echo "theocracy_government_levy_contribution_add";find . -iname "*.yml" -exec sed -i -b "s/^ theocracy_government_levy_contribution_add/ #theocracy_government_levy_contribution_add/g" {} +
echo "tribal_government_tax_contribution_mult";find . -iname "*.yml" -exec sed -i -b "s/^ tribal_government_tax_contribution_mult/ #tribal_government_tax_contribution_mult/g" {} +
echo "Xie";find . -iname "*.yml" -exec sed -i -b "s/^ Xie/ #Xie/g" {} +
echo "Run";find . -iname "*.yml" -exec sed -i -b "s/^ Run/ #Run/g" {} +
echo "Mao";find . -iname "*.yml" -exec sed -i -b "s/^ Mao/ #Mao/g" {} +
echo "Yeon";find . -iname "*.yml" -exec sed -i -b "s/^ Yeon/ #Yeon/g" {} +
echo "Luc";find . -iname "*.yml" -exec sed -i -b "s/^ Luc/ #Luc/g" {} +
echo "Tali";find . -iname "*.yml" -exec sed -i -b "s/^ Tali/ #Tali/g" {} +
echo "Shuli";find . -iname "*.yml" -exec sed -i -b "s/^ Shuli/ #Shuli/g" {} +
echo "Aitu";find . -iname "*.yml" -exec sed -i -b "s/^ Aitu/ #Aitu/g" {} +
echo "Asu";find . -iname "*.yml" -exec sed -i -b "s/^ Asu/ #Asu/g" {} +
echo "Akifusa";find . -iname "*.yml" -exec sed -i -b "s/^ Akifusa/ #Akifusa/g" {} +
echo "Akikage";find . -iname "*.yml" -exec sed -i -b "s/^ Akikage/ #Akikage/g" {} +
echo "Akimori";find . -iname "*.yml" -exec sed -i -b "s/^ Akimori/ #Akimori/g" {} +
echo "Akimoto";find . -iname "*.yml" -exec sed -i -b "s/^ Akimoto/ #Akimoto/g" {} +
echo "Akinaga";find . -iname "*.yml" -exec sed -i -b "s/^ Akinaga/ #Akinaga/g" {} +
echo "Akinao";find . -iname "*.yml" -exec sed -i -b "s/^ Akinao/ #Akinao/g" {} +
echo "Akisada";find . -iname "*.yml" -exec sed -i -b "s/^ Akisada/ #Akisada/g" {} +
echo "Akisuke";find . -iname "*.yml" -exec sed -i -b "s/^ Akisuke/ #Akisuke/g" {} +
echo "Akitada";find . -iname "*.yml" -exec sed -i -b "s/^ Akitada/ #Akitada/g" {} +
echo "Akitsugu";find . -iname "*.yml" -exec sed -i -b "s/^ Akitsugu/ #Akitsugu/g" {} +
echo "Akitsuna";find . -iname "*.yml" -exec sed -i -b "s/^ Akitsuna/ #Akitsuna/g" {} +
echo "Akiyasu";find . -iname "*.yml" -exec sed -i -b "s/^ Akiyasu/ #Akiyasu/g" {} +
echo "Akiyoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Akiyoshi/ #Akiyoshi/g" {} +
echo "Akizane";find . -iname "*.yml" -exec sed -i -b "s/^ Akizane/ #Akizane/g" {} +
echo "Anio";find . -iname "*.yml" -exec sed -i -b "s/^ Anio/ #Anio/g" {} +
echo "Arika";find . -iname "*.yml" -exec sed -i -b "s/^ Arika/ #Arika/g" {} +
echo "Arinaga";find . -iname "*.yml" -exec sed -i -b "s/^ Arinaga/ #Arinaga/g" {} +
echo "Arinobu";find . -iname "*.yml" -exec sed -i -b "s/^ Arinobu/ #Arinobu/g" {} +
echo "Ario";find . -iname "*.yml" -exec sed -i -b "s/^ Ario/ #Ario/g" {} +
echo "Ate";find . -iname "*.yml" -exec sed -i -b "s/^ Ate/ #Ate/g" {} +
echo "Aya";find . -iname "*.yml" -exec sed -i -b "s/^ Aya/ #Aya/g" {} +
echo "Azechi";find . -iname "*.yml" -exec sed -i -b "s/^ Azechi/ #Azechi/g" {} +
echo "Chikaie";find . -iname "*.yml" -exec sed -i -b "s/^ Chikaie/ #Chikaie/g" {} +
echo "Chikakata";find . -iname "*.yml" -exec sed -i -b "s/^ Chikakata/ #Chikakata/g" {} +
echo "Chikamasa";find . -iname "*.yml" -exec sed -i -b "s/^ Chikamasa/ #Chikamasa/g" {} +
echo "Chikamori";find . -iname "*.yml" -exec sed -i -b "s/^ Chikamori/ #Chikamori/g" {} +
echo "Chikamoto";find . -iname "*.yml" -exec sed -i -b "s/^ Chikamoto/ #Chikamoto/g" {} +
echo "Chikamune";find . -iname "*.yml" -exec sed -i -b "s/^ Chikamune/ #Chikamune/g" {} +
echo "Chikanaga";find . -iname "*.yml" -exec sed -i -b "s/^ Chikanaga/ #Chikanaga/g" {} +
echo "Chikanobu";find . -iname "*.yml" -exec sed -i -b "s/^ Chikanobu/ #Chikanobu/g" {} +
echo "Chikanori";find . -iname "*.yml" -exec sed -i -b "s/^ Chikanori/ #Chikanori/g" {} +
echo "Chikasada";find . -iname "*.yml" -exec sed -i -b "s/^ Chikasada/ #Chikasada/g" {} +
echo "Chikashige";find . -iname "*.yml" -exec sed -i -b "s/^ Chikashige/ #Chikashige/g" {} +
echo "Chikasue";find . -iname "*.yml" -exec sed -i -b "s/^ Chikasue/ #Chikasue/g" {} +
echo "Chikatada";find . -iname "*.yml" -exec sed -i -b "s/^ Chikatada/ #Chikatada/g" {} +
echo "Chikatoki";find . -iname "*.yml" -exec sed -i -b "s/^ Chikatoki/ #Chikatoki/g" {} +
echo "Chikatsune";find . -iname "*.yml" -exec sed -i -b "s/^ Chikatsune/ #Chikatsune/g" {} +
echo "Chikayasu";find . -iname "*.yml" -exec sed -i -b "s/^ Chikayasu/ #Chikayasu/g" {} +
echo "Chikayoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Chikayoshi/ #Chikayoshi/g" {} +
echo "Chikazane";find . -iname "*.yml" -exec sed -i -b "s/^ Chikazane/ #Chikazane/g" {} +
echo "Chiyo";find . -iname "*.yml" -exec sed -i -b "s/^ Chiyo/ #Chiyo/g" {} +
echo "Harukage";find . -iname "*.yml" -exec sed -i -b "s/^ Harukage/ #Harukage/g" {} +
echo "Harukiyo";find . -iname "*.yml" -exec sed -i -b "s/^ Harukiyo/ #Harukiyo/g" {} +
echo "Harutsugu";find . -iname "*.yml" -exec sed -i -b "s/^ Harutsugu/ #Harutsugu/g" {} +
echo "Haruyuki";find . -iname "*.yml" -exec sed -i -b "s/^ Haruyuki/ #Haruyuki/g" {} +
echo "Haruzumi";find . -iname "*.yml" -exec sed -i -b "s/^ Haruzumi/ #Haruzumi/g" {} +
echo "Hidehisa";find . -iname "*.yml" -exec sed -i -b "s/^ Hidehisa/ #Hidehisa/g" {} +
echo "Hidemoto";find . -iname "*.yml" -exec sed -i -b "s/^ Hidemoto/ #Hidemoto/g" {} +
echo "Hideo";find . -iname "*.yml" -exec sed -i -b "s/^ Hideo/ #Hideo/g" {} +
echo "Hidetaka";find . -iname "*.yml" -exec sed -i -b "s/^ Hidetaka/ #Hidetaka/g" {} +
echo "Hideyasu";find . -iname "*.yml" -exec sed -i -b "s/^ Hideyasu/ #Hideyasu/g" {} +
echo "Hideyoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Hideyoshi/ #Hideyoshi/g" {} +
echo "Hirofusa";find . -iname "*.yml" -exec sed -i -b "s/^ Hirofusa/ #Hirofusa/g" {} +
echo "Hiromitsu";find . -iname "*.yml" -exec sed -i -b "s/^ Hiromitsu/ #Hiromitsu/g" {} +
echo "Hironari";find . -iname "*.yml" -exec sed -i -b "s/^ Hironari/ #Hironari/g" {} +
echo "Hironobu";find . -iname "*.yml" -exec sed -i -b "s/^ Hironobu/ #Hironobu/g" {} +
echo "Hiroshi";find . -iname "*.yml" -exec sed -i -b "s/^ Hiroshi/ #Hiroshi/g" {} +
echo "Hirotaka";find . -iname "*.yml" -exec sed -i -b "s/^ Hirotaka/ #Hirotaka/g" {} +
echo "Hirotoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Hirotoshi/ #Hirotoshi/g" {} +
echo "Hirotsugu";find . -iname "*.yml" -exec sed -i -b "s/^ Hirotsugu/ #Hirotsugu/g" {} +
echo "Hirotsuna";find . -iname "*.yml" -exec sed -i -b "s/^ Hirotsuna/ #Hirotsuna/g" {} +
echo "Hiroyo";find . -iname "*.yml" -exec sed -i -b "s/^ Hiroyo/ #Hiroyo/g" {} +
echo "Hiroyori";find . -iname "*.yml" -exec sed -i -b "s/^ Hiroyori/ #Hiroyori/g" {} +
echo "Hiroyuki";find . -iname "*.yml" -exec sed -i -b "s/^ Hiroyuki/ #Hiroyuki/g" {} +
echo "Hisamasa";find . -iname "*.yml" -exec sed -i -b "s/^ Hisamasa/ #Hisamasa/g" {} +
echo "Hisamichi";find . -iname "*.yml" -exec sed -i -b "s/^ Hisamichi/ #Hisamichi/g" {} +
echo "Hisamori";find . -iname "*.yml" -exec sed -i -b "s/^ Hisamori/ #Hisamori/g" {} +
echo "Hisanaga";find . -iname "*.yml" -exec sed -i -b "s/^ Hisanaga/ #Hisanaga/g" {} +
echo "Hisanaka";find . -iname "*.yml" -exec sed -i -b "s/^ Hisanaka/ #Hisanaka/g" {} +
echo "Hisatada";find . -iname "*.yml" -exec sed -i -b "s/^ Hisatada/ #Hisatada/g" {} +
echo "Hisatsune";find . -iname "*.yml" -exec sed -i -b "s/^ Hisatsune/ #Hisatsune/g" {} +
echo "Hisayuki";find . -iname "*.yml" -exec sed -i -b "s/^ Hisayuki/ #Hisayuki/g" {} +
echo "Iechika";find . -iname "*.yml" -exec sed -i -b "s/^ Iechika/ #Iechika/g" {} +
echo "Iemasa";find . -iname "*.yml" -exec sed -i -b "s/^ Iemasa/ #Iemasa/g" {} +
echo "Iemori";find . -iname "*.yml" -exec sed -i -b "s/^ Iemori/ #Iemori/g" {} +
echo "Ienari";find . -iname "*.yml" -exec sed -i -b "s/^ Ienari/ #Ienari/g" {} +
echo "Ietoki";find . -iname "*.yml" -exec sed -i -b "s/^ Ietoki/ #Ietoki/g" {} +
echo "Ietoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Ietoshi/ #Ietoshi/g" {} +
echo "Ietsugu";find . -iname "*.yml" -exec sed -i -b "s/^ Ietsugu/ #Ietsugu/g" {} +
echo "Iyo";find . -iname "*.yml" -exec sed -i -b "s/^ Iyo/ #Iyo/g" {} +
echo "Kaga";find . -iname "*.yml" -exec sed -i -b "s/^ Kaga/ #Kaga/g" {} +
echo "Kageakira";find . -iname "*.yml" -exec sed -i -b "s/^ Kageakira/ #Kageakira/g" {} +
echo "Kagechika";find . -iname "*.yml" -exec sed -i -b "s/^ Kagechika/ #Kagechika/g" {} +
echo "Kagehiro";find . -iname "*.yml" -exec sed -i -b "s/^ Kagehiro/ #Kagehiro/g" {} +
echo "Kageie";find . -iname "*.yml" -exec sed -i -b "s/^ Kageie/ #Kageie/g" {} +
echo "Kagemasa";find . -iname "*.yml" -exec sed -i -b "s/^ Kagemasa/ #Kagemasa/g" {} +
echo "Kagemochi";find . -iname "*.yml" -exec sed -i -b "s/^ Kagemochi/ #Kagemochi/g" {} +
echo "Kagenobu";find . -iname "*.yml" -exec sed -i -b "s/^ Kagenobu/ #Kagenobu/g" {} +
echo "Kagenori";find . -iname "*.yml" -exec sed -i -b "s/^ Kagenori/ #Kagenori/g" {} +
echo "Kagetaka";find . -iname "*.yml" -exec sed -i -b "s/^ Kagetaka/ #Kagetaka/g" {} +
echo "Kagetoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Kagetoshi/ #Kagetoshi/g" {} +
echo "Kagetsugu";find . -iname "*.yml" -exec sed -i -b "s/^ Kagetsugu/ #Kagetsugu/g" {} +
echo "Kagetsuna";find . -iname "*.yml" -exec sed -i -b "s/^ Kagetsuna/ #Kagetsuna/g" {} +
echo "Kagetsura";find . -iname "*.yml" -exec sed -i -b "s/^ Kagetsura/ #Kagetsura/g" {} +
echo "Kageyori";find . -iname "*.yml" -exec sed -i -b "s/^ Kageyori/ #Kageyori/g" {} +
echo "Kageyoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Kageyoshi/ #Kageyoshi/g" {} +
echo "Kakuken";find . -iname "*.yml" -exec sed -i -b "s/^ Kakuken/ #Kakuken/g" {} +
echo "Kanemasa";find . -iname "*.yml" -exec sed -i -b "s/^ Kanemasa/ #Kanemasa/g" {} +
echo "Kanemori";find . -iname "*.yml" -exec sed -i -b "s/^ Kanemori/ #Kanemori/g" {} +
echo "Kanenaka";find . -iname "*.yml" -exec sed -i -b "s/^ Kanenaka/ #Kanenaka/g" {} +
echo "Kanesada";find . -iname "*.yml" -exec sed -i -b "s/^ Kanesada/ #Kanesada/g" {} +
echo "Kanesuke";find . -iname "*.yml" -exec sed -i -b "s/^ Kanesuke/ #Kanesuke/g" {} +
echo "Kasuga";find . -iname "*.yml" -exec sed -i -b "s/^ Kasuga/ #Kasuga/g" {} +
echo "Katsunaga";find . -iname "*.yml" -exec sed -i -b "s/^ Katsunaga/ #Katsunaga/g" {} +
echo "Katsuyoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Katsuyoshi/ #Katsuyoshi/g" {} +
echo "Kazumori";find . -iname "*.yml" -exec sed -i -b "s/^ Kazumori/ #Kazumori/g" {} +
echo "Kazunori";find . -iname "*.yml" -exec sed -i -b "s/^ Kazunori/ #Kazunori/g" {} +
echo "Kazuo";find . -iname "*.yml" -exec sed -i -b "s/^ Kazuo/ #Kazuo/g" {} +
echo "Kiyofusa";find . -iname "*.yml" -exec sed -i -b "s/^ Kiyofusa/ #Kiyofusa/g" {} +
echo "Kiyomasa";find . -iname "*.yml" -exec sed -i -b "s/^ Kiyomasa/ #Kiyomasa/g" {} +
echo "Kiyomoto";find . -iname "*.yml" -exec sed -i -b "s/^ Kiyomoto/ #Kiyomoto/g" {} +
echo "Kiyomune";find . -iname "*.yml" -exec sed -i -b "s/^ Kiyomune/ #Kiyomune/g" {} +
echo "Kiyonaga";find . -iname "*.yml" -exec sed -i -b "s/^ Kiyonaga/ #Kiyonaga/g" {} +
echo "Kiyonari";find . -iname "*.yml" -exec sed -i -b "s/^ Kiyonari/ #Kiyonari/g" {} +
echo "Kiyonori";find . -iname "*.yml" -exec sed -i -b "s/^ Kiyonori/ #Kiyonori/g" {} +
echo "Kiyoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Kiyoshi/ #Kiyoshi/g" {} +
echo "Kiyoshige";find . -iname "*.yml" -exec sed -i -b "s/^ Kiyoshige/ #Kiyoshige/g" {} +
echo "Kiyosue";find . -iname "*.yml" -exec sed -i -b "s/^ Kiyosue/ #Kiyosue/g" {} +
echo "Kiyotsuna";find . -iname "*.yml" -exec sed -i -b "s/^ Kiyotsuna/ #Kiyotsuna/g" {} +
echo "Kiyoyoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Kiyoyoshi/ #Kiyoyoshi/g" {} +
echo "Koremasa";find . -iname "*.yml" -exec sed -i -b "s/^ Koremasa/ #Koremasa/g" {} +
echo "Korenao";find . -iname "*.yml" -exec sed -i -b "s/^ Korenao/ #Korenao/g" {} +
echo "Korenori";find . -iname "*.yml" -exec sed -i -b "s/^ Korenori/ #Korenori/g" {} +
echo "Koretsuna";find . -iname "*.yml" -exec sed -i -b "s/^ Koretsuna/ #Koretsuna/g" {} +
echo "Koreyoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Koreyoshi/ #Koreyoshi/g" {} +
echo "Kuninori";find . -iname "*.yml" -exec sed -i -b "s/^ Kuninori/ #Kuninori/g" {} +
echo "Kunitsuna";find . -iname "*.yml" -exec sed -i -b "s/^ Kunitsuna/ #Kunitsuna/g" {} +
echo "Maro";find . -iname "*.yml" -exec sed -i -b "s/^ Maro/ #Maro/g" {} +
echo "Masachika";find . -iname "*.yml" -exec sed -i -b "s/^ Masachika/ #Masachika/g" {} +
echo "Masafusa";find . -iname "*.yml" -exec sed -i -b "s/^ Masafusa/ #Masafusa/g" {} +
echo "Masahiro";find . -iname "*.yml" -exec sed -i -b "s/^ Masahiro/ #Masahiro/g" {} +
echo "Masaie";find . -iname "*.yml" -exec sed -i -b "s/^ Masaie/ #Masaie/g" {} +
echo "Masakage";find . -iname "*.yml" -exec sed -i -b "s/^ Masakage/ #Masakage/g" {} +
echo "Masaki";find . -iname "*.yml" -exec sed -i -b "s/^ Masaki/ #Masaki/g" {} +
echo "Masako";find . -iname "*.yml" -exec sed -i -b "s/^ Masako/ #Masako/g" {} +
echo "Masakuni";find . -iname "*.yml" -exec sed -i -b "s/^ Masakuni/ #Masakuni/g" {} +
echo "Masamitsu";find . -iname "*.yml" -exec sed -i -b "s/^ Masamitsu/ #Masamitsu/g" {} +
echo "Masamori";find . -iname "*.yml" -exec sed -i -b "s/^ Masamori/ #Masamori/g" {} +
echo "Masamoto";find . -iname "*.yml" -exec sed -i -b "s/^ Masamoto/ #Masamoto/g" {} +
echo "Masamune";find . -iname "*.yml" -exec sed -i -b "s/^ Masamune/ #Masamune/g" {} +
echo "Masanaga";find . -iname "*.yml" -exec sed -i -b "s/^ Masanaga/ #Masanaga/g" {} +
echo "Masanari";find . -iname "*.yml" -exec sed -i -b "s/^ Masanari/ #Masanari/g" {} +
echo "Masanobu";find . -iname "*.yml" -exec sed -i -b "s/^ Masanobu/ #Masanobu/g" {} +
echo "Masanori";find . -iname "*.yml" -exec sed -i -b "s/^ Masanori/ #Masanori/g" {} +
echo "Masaru";find . -iname "*.yml" -exec sed -i -b "s/^ Masaru/ #Masaru/g" {} +
echo "Masasada";find . -iname "*.yml" -exec sed -i -b "s/^ Masasada/ #Masasada/g" {} +
echo "Masashi";find . -iname "*.yml" -exec sed -i -b "s/^ Masashi/ #Masashi/g" {} +
echo "Masashige";find . -iname "*.yml" -exec sed -i -b "s/^ Masashige/ #Masashige/g" {} +
echo "Masatada";find . -iname "*.yml" -exec sed -i -b "s/^ Masatada/ #Masatada/g" {} +
echo "Masatomo";find . -iname "*.yml" -exec sed -i -b "s/^ Masatomo/ #Masatomo/g" {} +
echo "Masatoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Masatoshi/ #Masatoshi/g" {} +
echo "Masatsugu";find . -iname "*.yml" -exec sed -i -b "s/^ Masatsugu/ #Masatsugu/g" {} +
echo "Masatsuna";find . -iname "*.yml" -exec sed -i -b "s/^ Masatsuna/ #Masatsuna/g" {} +
echo "Masatsune";find . -iname "*.yml" -exec sed -i -b "s/^ Masatsune/ #Masatsune/g" {} +
echo "Masayasu";find . -iname "*.yml" -exec sed -i -b "s/^ Masayasu/ #Masayasu/g" {} +
echo "Masayori";find . -iname "*.yml" -exec sed -i -b "s/^ Masayori/ #Masayori/g" {} +
echo "Masayoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Masayoshi/ #Masayoshi/g" {} +
echo "Masayuki";find . -iname "*.yml" -exec sed -i -b "s/^ Masayuki/ #Masayuki/g" {} +
echo "Masazane";find . -iname "*.yml" -exec sed -i -b "s/^ Masazane/ #Masazane/g" {} +
echo "Masazumi";find . -iname "*.yml" -exec sed -i -b "s/^ Masazumi/ #Masazumi/g" {} +
echo "Michimori";find . -iname "*.yml" -exec sed -i -b "s/^ Michimori/ #Michimori/g" {} +
echo "Michinao";find . -iname "*.yml" -exec sed -i -b "s/^ Michinao/ #Michinao/g" {} +
echo "Michinobu";find . -iname "*.yml" -exec sed -i -b "s/^ Michinobu/ #Michinobu/g" {} +
echo "Michisue";find . -iname "*.yml" -exec sed -i -b "s/^ Michisue/ #Michisue/g" {} +
echo "Michitoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Michitoshi/ #Michitoshi/g" {} +
echo "Michiyasu";find . -iname "*.yml" -exec sed -i -b "s/^ Michiyasu/ #Michiyasu/g" {} +
echo "Michiyoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Michiyoshi/ #Michiyoshi/g" {} +
echo "Mitsuchika";find . -iname "*.yml" -exec sed -i -b "s/^ Mitsuchika/ #Mitsuchika/g" {} +
echo "Mitsufusa";find . -iname "*.yml" -exec sed -i -b "s/^ Mitsufusa/ #Mitsufusa/g" {} +
echo "Mitsuharu";find . -iname "*.yml" -exec sed -i -b "s/^ Mitsuharu/ #Mitsuharu/g" {} +
echo "Mitsukuni";find . -iname "*.yml" -exec sed -i -b "s/^ Mitsukuni/ #Mitsukuni/g" {} +
echo "Mitsumune";find . -iname "*.yml" -exec sed -i -b "s/^ Mitsumune/ #Mitsumune/g" {} +
echo "Mitsunari";find . -iname "*.yml" -exec sed -i -b "s/^ Mitsunari/ #Mitsunari/g" {} +
echo "Mitsunobu";find . -iname "*.yml" -exec sed -i -b "s/^ Mitsunobu/ #Mitsunobu/g" {} +
echo "Mitsushige";find . -iname "*.yml" -exec sed -i -b "s/^ Mitsushige/ #Mitsushige/g" {} +
echo "Mitsusuke";find . -iname "*.yml" -exec sed -i -b "s/^ Mitsusuke/ #Mitsusuke/g" {} +
echo "Mitsutada";find . -iname "*.yml" -exec sed -i -b "s/^ Mitsutada/ #Mitsutada/g" {} +
echo "Mitsutsuna";find . -iname "*.yml" -exec sed -i -b "s/^ Mitsutsuna/ #Mitsutsuna/g" {} +
echo "Mitsuyasu";find . -iname "*.yml" -exec sed -i -b "s/^ Mitsuyasu/ #Mitsuyasu/g" {} +
echo "Mitsuyori";find . -iname "*.yml" -exec sed -i -b "s/^ Mitsuyori/ #Mitsuyori/g" {} +
echo "Mitsuyoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Mitsuyoshi/ #Mitsuyoshi/g" {} +
echo "Mochinaga";find . -iname "*.yml" -exec sed -i -b "s/^ Mochinaga/ #Mochinaga/g" {} +
echo "Mochitaka";find . -iname "*.yml" -exec sed -i -b "s/^ Mochitaka/ #Mochitaka/g" {} +
echo "Morichika";find . -iname "*.yml" -exec sed -i -b "s/^ Morichika/ #Morichika/g" {} +
echo "Morihiro";find . -iname "*.yml" -exec sed -i -b "s/^ Morihiro/ #Morihiro/g" {} +
echo "Morikiyo";find . -iname "*.yml" -exec sed -i -b "s/^ Morikiyo/ #Morikiyo/g" {} +
echo "Morikuni";find . -iname "*.yml" -exec sed -i -b "s/^ Morikuni/ #Morikuni/g" {} +
echo "Morimasa";find . -iname "*.yml" -exec sed -i -b "s/^ Morimasa/ #Morimasa/g" {} +
echo "Morimitsu";find . -iname "*.yml" -exec sed -i -b "s/^ Morimitsu/ #Morimitsu/g" {} +
echo "Morimune";find . -iname "*.yml" -exec sed -i -b "s/^ Morimune/ #Morimune/g" {} +
echo "Morinaga";find . -iname "*.yml" -exec sed -i -b "s/^ Morinaga/ #Morinaga/g" {} +
echo "Morinari";find . -iname "*.yml" -exec sed -i -b "s/^ Morinari/ #Morinari/g" {} +
echo "Morinobu";find . -iname "*.yml" -exec sed -i -b "s/^ Morinobu/ #Morinobu/g" {} +
echo "Morioki";find . -iname "*.yml" -exec sed -i -b "s/^ Morioki/ #Morioki/g" {} +
echo "Morishige";find . -iname "*.yml" -exec sed -i -b "s/^ Morishige/ #Morishige/g" {} +
echo "Moritaka";find . -iname "*.yml" -exec sed -i -b "s/^ Moritaka/ #Moritaka/g" {} +
echo "Moritsuna";find . -iname "*.yml" -exec sed -i -b "s/^ Moritsuna/ #Moritsuna/g" {} +
echo "Moriyasu";find . -iname "*.yml" -exec sed -i -b "s/^ Moriyasu/ #Moriyasu/g" {} +
echo "Morizane";find . -iname "*.yml" -exec sed -i -b "s/^ Morizane/ #Morizane/g" {} +
echo "Motochika";find . -iname "*.yml" -exec sed -i -b "s/^ Motochika/ #Motochika/g" {} +
echo "Motoharu";find . -iname "*.yml" -exec sed -i -b "s/^ Motoharu/ #Motoharu/g" {} +
echo "Motoie";find . -iname "*.yml" -exec sed -i -b "s/^ Motoie/ #Motoie/g" {} +
echo "Motokage";find . -iname "*.yml" -exec sed -i -b "s/^ Motokage/ #Motokage/g" {} +
echo "Motokiyo";find . -iname "*.yml" -exec sed -i -b "s/^ Motokiyo/ #Motokiyo/g" {} +
echo "Motokuni";find . -iname "*.yml" -exec sed -i -b "s/^ Motokuni/ #Motokuni/g" {} +
echo "Motomune";find . -iname "*.yml" -exec sed -i -b "s/^ Motomune/ #Motomune/g" {} +
echo "Motonaga";find . -iname "*.yml" -exec sed -i -b "s/^ Motonaga/ #Motonaga/g" {} +
echo "Motonari";find . -iname "*.yml" -exec sed -i -b "s/^ Motonari/ #Motonari/g" {} +
echo "Motonobu";find . -iname "*.yml" -exec sed -i -b "s/^ Motonobu/ #Motonobu/g" {} +
echo "Motonori";find . -iname "*.yml" -exec sed -i -b "s/^ Motonori/ #Motonori/g" {} +
echo "Motosada";find . -iname "*.yml" -exec sed -i -b "s/^ Motosada/ #Motosada/g" {} +
echo "Motosuke";find . -iname "*.yml" -exec sed -i -b "s/^ Motosuke/ #Motosuke/g" {} +
echo "Mototada";find . -iname "*.yml" -exec sed -i -b "s/^ Mototada/ #Mototada/g" {} +
echo "Mototaka";find . -iname "*.yml" -exec sed -i -b "s/^ Mototaka/ #Mototaka/g" {} +
echo "Mototsuna";find . -iname "*.yml" -exec sed -i -b "s/^ Mototsuna/ #Mototsuna/g" {} +
echo "Motoyasu";find . -iname "*.yml" -exec sed -i -b "s/^ Motoyasu/ #Motoyasu/g" {} +
echo "Motoyoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Motoyoshi/ #Motoyoshi/g" {} +
echo "Motozane";find . -iname "*.yml" -exec sed -i -b "s/^ Motozane/ #Motozane/g" {} +
echo "Munefusa";find . -iname "*.yml" -exec sed -i -b "s/^ Munefusa/ #Munefusa/g" {} +
echo "Munehisa";find . -iname "*.yml" -exec sed -i -b "s/^ Munehisa/ #Munehisa/g" {} +
echo "Muneie";find . -iname "*.yml" -exec sed -i -b "s/^ Muneie/ #Muneie/g" {} +
echo "Munekage";find . -iname "*.yml" -exec sed -i -b "s/^ Munekage/ #Munekage/g" {} +
echo "Munemasa";find . -iname "*.yml" -exec sed -i -b "s/^ Munemasa/ #Munemasa/g" {} +
echo "Munemura";find . -iname "*.yml" -exec sed -i -b "s/^ Munemura/ #Munemura/g" {} +
echo "Munenobu";find . -iname "*.yml" -exec sed -i -b "s/^ Munenobu/ #Munenobu/g" {} +
echo "Munenori";find . -iname "*.yml" -exec sed -i -b "s/^ Munenori/ #Munenori/g" {} +
echo "Munetaka";find . -iname "*.yml" -exec sed -i -b "s/^ Munetaka/ #Munetaka/g" {} +
echo "Munetoki";find . -iname "*.yml" -exec sed -i -b "s/^ Munetoki/ #Munetoki/g" {} +
echo "Munetsuna";find . -iname "*.yml" -exec sed -i -b "s/^ Munetsuna/ #Munetsuna/g" {} +
echo "Muneuji";find . -iname "*.yml" -exec sed -i -b "s/^ Muneuji/ #Muneuji/g" {} +
echo "Muneyoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Muneyoshi/ #Muneyoshi/g" {} +
echo "Muneyuki";find . -iname "*.yml" -exec sed -i -b "s/^ Muneyuki/ #Muneyuki/g" {} +
echo "Munezane";find . -iname "*.yml" -exec sed -i -b "s/^ Munezane/ #Munezane/g" {} +
echo "Nagachika";find . -iname "*.yml" -exec sed -i -b "s/^ Nagachika/ #Nagachika/g" {} +
echo "Nagafusa";find . -iname "*.yml" -exec sed -i -b "s/^ Nagafusa/ #Nagafusa/g" {} +
echo "Nagamasa";find . -iname "*.yml" -exec sed -i -b "s/^ Nagamasa/ #Nagamasa/g" {} +
echo "Nagamochi";find . -iname "*.yml" -exec sed -i -b "s/^ Nagamochi/ #Nagamochi/g" {} +
echo "Nagamori";find . -iname "*.yml" -exec sed -i -b "s/^ Nagamori/ #Nagamori/g" {} +
echo "Nagamoto";find . -iname "*.yml" -exec sed -i -b "s/^ Nagamoto/ #Nagamoto/g" {} +
echo "Naganari";find . -iname "*.yml" -exec sed -i -b "s/^ Naganari/ #Naganari/g" {} +
echo "Naganobu";find . -iname "*.yml" -exec sed -i -b "s/^ Naganobu/ #Naganobu/g" {} +
echo "Naganori";find . -iname "*.yml" -exec sed -i -b "s/^ Naganori/ #Naganori/g" {} +
echo "Nagataka";find . -iname "*.yml" -exec sed -i -b "s/^ Nagataka/ #Nagataka/g" {} +
echo "Nagatsune";find . -iname "*.yml" -exec sed -i -b "s/^ Nagatsune/ #Nagatsune/g" {} +
echo "Nagayasu";find . -iname "*.yml" -exec sed -i -b "s/^ Nagayasu/ #Nagayasu/g" {} +
echo "Nagayori";find . -iname "*.yml" -exec sed -i -b "s/^ Nagayori/ #Nagayori/g" {} +
echo "Nagayuki";find . -iname "*.yml" -exec sed -i -b "s/^ Nagayuki/ #Nagayuki/g" {} +
echo "Nagazane";find . -iname "*.yml" -exec sed -i -b "s/^ Nagazane/ #Nagazane/g" {} +
echo "Naoie";find . -iname "*.yml" -exec sed -i -b "s/^ Naoie/ #Naoie/g" {} +
echo "Naomasa";find . -iname "*.yml" -exec sed -i -b "s/^ Naomasa/ #Naomasa/g" {} +
echo "Naomoto";find . -iname "*.yml" -exec sed -i -b "s/^ Naomoto/ #Naomoto/g" {} +
echo "Naotsune";find . -iname "*.yml" -exec sed -i -b "s/^ Naotsune/ #Naotsune/g" {} +
echo "Naoyuki";find . -iname "*.yml" -exec sed -i -b "s/^ Naoyuki/ #Naoyuki/g" {} +
echo "Narikata";find . -iname "*.yml" -exec sed -i -b "s/^ Narikata/ #Narikata/g" {} +
echo "Narikuni";find . -iname "*.yml" -exec sed -i -b "s/^ Narikuni/ #Narikuni/g" {} +
echo "Narimasa";find . -iname "*.yml" -exec sed -i -b "s/^ Narimasa/ #Narimasa/g" {} +
echo "Narimori";find . -iname "*.yml" -exec sed -i -b "s/^ Narimori/ #Narimori/g" {} +
echo "Narinobu";find . -iname "*.yml" -exec sed -i -b "s/^ Narinobu/ #Narinobu/g" {} +
echo "Narisuke";find . -iname "*.yml" -exec sed -i -b "s/^ Narisuke/ #Narisuke/g" {} +
echo "Naritada";find . -iname "*.yml" -exec sed -i -b "s/^ Naritada/ #Naritada/g" {} +
echo "Nariyoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Nariyoshi/ #Nariyoshi/g" {} +
echo "Natsumi";find . -iname "*.yml" -exec sed -i -b "s/^ Natsumi/ #Natsumi/g" {} +
echo "Noboru";find . -iname "*.yml" -exec sed -i -b "s/^ Noboru/ #Noboru/g" {} +
echo "Nobuchika";find . -iname "*.yml" -exec sed -i -b "s/^ Nobuchika/ #Nobuchika/g" {} +
echo "Nobufusa";find . -iname "*.yml" -exec sed -i -b "s/^ Nobufusa/ #Nobufusa/g" {} +
echo "Nobuhira";find . -iname "*.yml" -exec sed -i -b "s/^ Nobuhira/ #Nobuhira/g" {} +
echo "Nobukiyo";find . -iname "*.yml" -exec sed -i -b "s/^ Nobukiyo/ #Nobukiyo/g" {} +
echo "Nobumasa";find . -iname "*.yml" -exec sed -i -b "s/^ Nobumasa/ #Nobumasa/g" {} +
echo "Nobumitsu";find . -iname "*.yml" -exec sed -i -b "s/^ Nobumitsu/ #Nobumitsu/g" {} +
echo "Nobumori";find . -iname "*.yml" -exec sed -i -b "s/^ Nobumori/ #Nobumori/g" {} +
echo "Nobumoto";find . -iname "*.yml" -exec sed -i -b "s/^ Nobumoto/ #Nobumoto/g" {} +
echo "Nobunaga";find . -iname "*.yml" -exec sed -i -b "s/^ Nobunaga/ #Nobunaga/g" {} +
echo "Nobunari";find . -iname "*.yml" -exec sed -i -b "s/^ Nobunari/ #Nobunari/g" {} +
echo "Nobunori";find . -iname "*.yml" -exec sed -i -b "s/^ Nobunori/ #Nobunori/g" {} +
echo "Nobusada";find . -iname "*.yml" -exec sed -i -b "s/^ Nobusada/ #Nobusada/g" {} +
echo "Nobushige";find . -iname "*.yml" -exec sed -i -b "s/^ Nobushige/ #Nobushige/g" {} +
echo "Nobutada";find . -iname "*.yml" -exec sed -i -b "s/^ Nobutada/ #Nobutada/g" {} +
echo "Nobutaka";find . -iname "*.yml" -exec sed -i -b "s/^ Nobutaka/ #Nobutaka/g" {} +
echo "Nobutsuna";find . -iname "*.yml" -exec sed -i -b "s/^ Nobutsuna/ #Nobutsuna/g" {} +
echo "Nobutsune";find . -iname "*.yml" -exec sed -i -b "s/^ Nobutsune/ #Nobutsune/g" {} +
echo "Nobuyasu";find . -iname "*.yml" -exec sed -i -b "s/^ Nobuyasu/ #Nobuyasu/g" {} +
echo "Nobuyoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Nobuyoshi/ #Nobuyoshi/g" {} +
echo "Nobuyuki";find . -iname "*.yml" -exec sed -i -b "s/^ Nobuyuki/ #Nobuyuki/g" {} +
echo "Nobuzumi";find . -iname "*.yml" -exec sed -i -b "s/^ Nobuzumi/ #Nobuzumi/g" {} +
echo "Norifusa";find . -iname "*.yml" -exec sed -i -b "s/^ Norifusa/ #Norifusa/g" {} +
echo "Norihito";find . -iname "*.yml" -exec sed -i -b "s/^ Norihito/ #Norihito/g" {} +
echo "Norikage";find . -iname "*.yml" -exec sed -i -b "s/^ Norikage/ #Norikage/g" {} +
echo "Norikata";find . -iname "*.yml" -exec sed -i -b "s/^ Norikata/ #Norikata/g" {} +
echo "Norikuni";find . -iname "*.yml" -exec sed -i -b "s/^ Norikuni/ #Norikuni/g" {} +
echo "Norimasa";find . -iname "*.yml" -exec sed -i -b "s/^ Norimasa/ #Norimasa/g" {} +
echo "Norimochi";find . -iname "*.yml" -exec sed -i -b "s/^ Norimochi/ #Norimochi/g" {} +
echo "Norimoto";find . -iname "*.yml" -exec sed -i -b "s/^ Norimoto/ #Norimoto/g" {} +
echo "Norinari";find . -iname "*.yml" -exec sed -i -b "s/^ Norinari/ #Norinari/g" {} +
echo "Norinobu";find . -iname "*.yml" -exec sed -i -b "s/^ Norinobu/ #Norinobu/g" {} +
echo "Norisada";find . -iname "*.yml" -exec sed -i -b "s/^ Norisada/ #Norisada/g" {} +
echo "Norishige";find . -iname "*.yml" -exec sed -i -b "s/^ Norishige/ #Norishige/g" {} +
echo "Norisuke";find . -iname "*.yml" -exec sed -i -b "s/^ Norisuke/ #Norisuke/g" {} +
echo "Noritada";find . -iname "*.yml" -exec sed -i -b "s/^ Noritada/ #Noritada/g" {} +
echo "Noritaka";find . -iname "*.yml" -exec sed -i -b "s/^ Noritaka/ #Noritaka/g" {} +
echo "Noritoki";find . -iname "*.yml" -exec sed -i -b "s/^ Noritoki/ #Noritoki/g" {} +
echo "Noriyori";find . -iname "*.yml" -exec sed -i -b "s/^ Noriyori/ #Noriyori/g" {} +
echo "Noriyoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Noriyoshi/ #Noriyoshi/g" {} +
echo "Norizane";find . -iname "*.yml" -exec sed -i -b "s/^ Norizane/ #Norizane/g" {} +
echo "Osamu";find . -iname "*.yml" -exec sed -i -b "s/^ Osamu/ #Osamu/g" {} +
echo "Sadachika";find . -iname "*.yml" -exec sed -i -b "s/^ Sadachika/ #Sadachika/g" {} +
echo "Sadakage";find . -iname "*.yml" -exec sed -i -b "s/^ Sadakage/ #Sadakage/g" {} +
echo "Sadakuni";find . -iname "*.yml" -exec sed -i -b "s/^ Sadakuni/ #Sadakuni/g" {} +
echo "Sadamichi";find . -iname "*.yml" -exec sed -i -b "s/^ Sadamichi/ #Sadamichi/g" {} +
echo "Sadamitsu";find . -iname "*.yml" -exec sed -i -b "s/^ Sadamitsu/ #Sadamitsu/g" {} +
echo "Sadamune";find . -iname "*.yml" -exec sed -i -b "s/^ Sadamune/ #Sadamune/g" {} +
echo "Sadanaga";find . -iname "*.yml" -exec sed -i -b "s/^ Sadanaga/ #Sadanaga/g" {} +
echo "Sadanao";find . -iname "*.yml" -exec sed -i -b "s/^ Sadanao/ #Sadanao/g" {} +
echo "Sadanobu";find . -iname "*.yml" -exec sed -i -b "s/^ Sadanobu/ #Sadanobu/g" {} +
echo "Sadanori";find . -iname "*.yml" -exec sed -i -b "s/^ Sadanori/ #Sadanori/g" {} +
echo "Sadaoki";find . -iname "*.yml" -exec sed -i -b "s/^ Sadaoki/ #Sadaoki/g" {} +
echo "Sadaomi";find . -iname "*.yml" -exec sed -i -b "s/^ Sadaomi/ #Sadaomi/g" {} +
echo "Sadashige";find . -iname "*.yml" -exec sed -i -b "s/^ Sadashige/ #Sadashige/g" {} +
echo "Sadasuke";find . -iname "*.yml" -exec sed -i -b "s/^ Sadasuke/ #Sadasuke/g" {} +
echo "Sadataka";find . -iname "*.yml" -exec sed -i -b "s/^ Sadataka/ #Sadataka/g" {} +
echo "Sadatoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Sadatoshi/ #Sadatoshi/g" {} +
echo "Sadatsugu";find . -iname "*.yml" -exec sed -i -b "s/^ Sadatsugu/ #Sadatsugu/g" {} +
echo "Sadatsuna";find . -iname "*.yml" -exec sed -i -b "s/^ Sadatsuna/ #Sadatsuna/g" {} +
echo "Sadayo";find . -iname "*.yml" -exec sed -i -b "s/^ Sadayo/ #Sadayo/g" {} +
echo "Sadayori";find . -iname "*.yml" -exec sed -i -b "s/^ Sadayori/ #Sadayori/g" {} +
echo "Sadayoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Sadayoshi/ #Sadayoshi/g" {} +
echo "Sadayuki";find . -iname "*.yml" -exec sed -i -b "s/^ Sadayuki/ #Sadayuki/g" {} +
echo "Sakinobu";find . -iname "*.yml" -exec sed -i -b "s/^ Sakinobu/ #Sakinobu/g" {} +
echo "Sanechika";find . -iname "*.yml" -exec sed -i -b "s/^ Sanechika/ #Sanechika/g" {} +
echo "Sanemitsu";find . -iname "*.yml" -exec sed -i -b "s/^ Sanemitsu/ #Sanemitsu/g" {} +
echo "Sanemoto";find . -iname "*.yml" -exec sed -i -b "s/^ Sanemoto/ #Sanemoto/g" {} +
echo "Sanesue";find . -iname "*.yml" -exec sed -i -b "s/^ Sanesue/ #Sanesue/g" {} +
echo "Sanetomo";find . -iname "*.yml" -exec sed -i -b "s/^ Sanetomo/ #Sanetomo/g" {} +
echo "Saneyori";find . -iname "*.yml" -exec sed -i -b "s/^ Saneyori/ #Saneyori/g" {} +
echo "Satoru";find . -iname "*.yml" -exec sed -i -b "s/^ Satoru/ #Satoru/g" {} +
echo "Satoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Satoshi/ #Satoshi/g" {} +
echo "Shigefusa";find . -iname "*.yml" -exec sed -i -b "s/^ Shigefusa/ #Shigefusa/g" {} +
echo "Shigeharu";find . -iname "*.yml" -exec sed -i -b "s/^ Shigeharu/ #Shigeharu/g" {} +
echo "Shigehide";find . -iname "*.yml" -exec sed -i -b "s/^ Shigehide/ #Shigehide/g" {} +
echo "Shigehira";find . -iname "*.yml" -exec sed -i -b "s/^ Shigehira/ #Shigehira/g" {} +
echo "Shigeie";find . -iname "*.yml" -exec sed -i -b "s/^ Shigeie/ #Shigeie/g" {} +
echo "Shigekane";find . -iname "*.yml" -exec sed -i -b "s/^ Shigekane/ #Shigekane/g" {} +
echo "Shigekiyo";find . -iname "*.yml" -exec sed -i -b "s/^ Shigekiyo/ #Shigekiyo/g" {} +
echo "Shigemasa";find . -iname "*.yml" -exec sed -i -b "s/^ Shigemasa/ #Shigemasa/g" {} +
echo "Shigemochi";find . -iname "*.yml" -exec sed -i -b "s/^ Shigemochi/ #Shigemochi/g" {} +
echo "Shigemoto";find . -iname "*.yml" -exec sed -i -b "s/^ Shigemoto/ #Shigemoto/g" {} +
echo "Shigemune";find . -iname "*.yml" -exec sed -i -b "s/^ Shigemune/ #Shigemune/g" {} +
echo "Shigenaga";find . -iname "*.yml" -exec sed -i -b "s/^ Shigenaga/ #Shigenaga/g" {} +
echo "Shigenari";find . -iname "*.yml" -exec sed -i -b "s/^ Shigenari/ #Shigenari/g" {} +
echo "Shigenobu";find . -iname "*.yml" -exec sed -i -b "s/^ Shigenobu/ #Shigenobu/g" {} +
echo "Shigenori";find . -iname "*.yml" -exec sed -i -b "s/^ Shigenori/ #Shigenori/g" {} +
echo "Shigesada";find . -iname "*.yml" -exec sed -i -b "s/^ Shigesada/ #Shigesada/g" {} +
echo "Shigesato";find . -iname "*.yml" -exec sed -i -b "s/^ Shigesato/ #Shigesato/g" {} +
echo "Shigesue";find . -iname "*.yml" -exec sed -i -b "s/^ Shigesue/ #Shigesue/g" {} +
echo "Shigetada";find . -iname "*.yml" -exec sed -i -b "s/^ Shigetada/ #Shigetada/g" {} +
echo "Shigetaka";find . -iname "*.yml" -exec sed -i -b "s/^ Shigetaka/ #Shigetaka/g" {} +
echo "Shigetake";find . -iname "*.yml" -exec sed -i -b "s/^ Shigetake/ #Shigetake/g" {} +
echo "Shigetane";find . -iname "*.yml" -exec sed -i -b "s/^ Shigetane/ #Shigetane/g" {} +
echo "Shigetomo";find . -iname "*.yml" -exec sed -i -b "s/^ Shigetomo/ #Shigetomo/g" {} +
echo "Shigetoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Shigetoshi/ #Shigetoshi/g" {} +
echo "Shigetsugu";find . -iname "*.yml" -exec sed -i -b "s/^ Shigetsugu/ #Shigetsugu/g" {} +
echo "Shigetsuna";find . -iname "*.yml" -exec sed -i -b "s/^ Shigetsuna/ #Shigetsuna/g" {} +
echo "Shigetsune";find . -iname "*.yml" -exec sed -i -b "s/^ Shigetsune/ #Shigetsune/g" {} +
echo "Shigeyasu";find . -iname "*.yml" -exec sed -i -b "s/^ Shigeyasu/ #Shigeyasu/g" {} +
echo "Shigeyoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Shigeyoshi/ #Shigeyoshi/g" {} +
echo "Shigezane";find . -iname "*.yml" -exec sed -i -b "s/^ Shigezane/ #Shigezane/g" {} +
echo "Shizuka";find . -iname "*.yml" -exec sed -i -b "s/^ Shizuka/ #Shizuka/g" {} +
echo "Suehiro";find . -iname "*.yml" -exec sed -i -b "s/^ Suehiro/ #Suehiro/g" {} +
echo "Sukehiro";find . -iname "*.yml" -exec sed -i -b "s/^ Sukehiro/ #Sukehiro/g" {} +
echo "Sukemasa";find . -iname "*.yml" -exec sed -i -b "s/^ Sukemasa/ #Sukemasa/g" {} +
echo "Sukemitsu";find . -iname "*.yml" -exec sed -i -b "s/^ Sukemitsu/ #Sukemitsu/g" {} +
echo "Sukemori";find . -iname "*.yml" -exec sed -i -b "s/^ Sukemori/ #Sukemori/g" {} +
echo "Sukenaga";find . -iname "*.yml" -exec sed -i -b "s/^ Sukenaga/ #Sukenaga/g" {} +
echo "Sukenao";find . -iname "*.yml" -exec sed -i -b "s/^ Sukenao/ #Sukenao/g" {} +
echo "Sukenori";find . -iname "*.yml" -exec sed -i -b "s/^ Sukenori/ #Sukenori/g" {} +
echo "Suketada";find . -iname "*.yml" -exec sed -i -b "s/^ Suketada/ #Suketada/g" {} +
echo "Suketaka";find . -iname "*.yml" -exec sed -i -b "s/^ Suketaka/ #Suketaka/g" {} +
echo "Suketoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Suketoshi/ #Suketoshi/g" {} +
echo "Sukeyasu";find . -iname "*.yml" -exec sed -i -b "s/^ Sukeyasu/ #Sukeyasu/g" {} +
echo "Tadachika";find . -iname "*.yml" -exec sed -i -b "s/^ Tadachika/ #Tadachika/g" {} +
echo "Tadahiro";find . -iname "*.yml" -exec sed -i -b "s/^ Tadahiro/ #Tadahiro/g" {} +
echo "Tadahisa";find . -iname "*.yml" -exec sed -i -b "s/^ Tadahisa/ #Tadahisa/g" {} +
echo "Tadaie";find . -iname "*.yml" -exec sed -i -b "s/^ Tadaie/ #Tadaie/g" {} +
echo "Tadakuni";find . -iname "*.yml" -exec sed -i -b "s/^ Tadakuni/ #Tadakuni/g" {} +
echo "Tadamasa";find . -iname "*.yml" -exec sed -i -b "s/^ Tadamasa/ #Tadamasa/g" {} +
echo "Tadamichi";find . -iname "*.yml" -exec sed -i -b "s/^ Tadamichi/ #Tadamichi/g" {} +
echo "Tadamochi";find . -iname "*.yml" -exec sed -i -b "s/^ Tadamochi/ #Tadamochi/g" {} +
echo "Tadamoto";find . -iname "*.yml" -exec sed -i -b "s/^ Tadamoto/ #Tadamoto/g" {} +
echo "Tadamune";find . -iname "*.yml" -exec sed -i -b "s/^ Tadamune/ #Tadamune/g" {} +
echo "Tadanao";find . -iname "*.yml" -exec sed -i -b "s/^ Tadanao/ #Tadanao/g" {} +
echo "Tadanari";find . -iname "*.yml" -exec sed -i -b "s/^ Tadanari/ #Tadanari/g" {} +
echo "Tadaoki";find . -iname "*.yml" -exec sed -i -b "s/^ Tadaoki/ #Tadaoki/g" {} +
echo "Tadasuke";find . -iname "*.yml" -exec sed -i -b "s/^ Tadasuke/ #Tadasuke/g" {} +
echo "Tadataka";find . -iname "*.yml" -exec sed -i -b "s/^ Tadataka/ #Tadataka/g" {} +
echo "Tadatoki";find . -iname "*.yml" -exec sed -i -b "s/^ Tadatoki/ #Tadatoki/g" {} +
echo "Tadatomo";find . -iname "*.yml" -exec sed -i -b "s/^ Tadatomo/ #Tadatomo/g" {} +
echo "Tadatoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Tadatoshi/ #Tadatoshi/g" {} +
echo "Tadatsune";find . -iname "*.yml" -exec sed -i -b "s/^ Tadatsune/ #Tadatsune/g" {} +
echo "Tadayoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Tadayoshi/ #Tadayoshi/g" {} +
echo "Tadayuki";find . -iname "*.yml" -exec sed -i -b "s/^ Tadayuki/ #Tadayuki/g" {} +
echo "Tadazumi";find . -iname "*.yml" -exec sed -i -b "s/^ Tadazumi/ #Tadazumi/g" {} +
echo "Takachika";find . -iname "*.yml" -exec sed -i -b "s/^ Takachika/ #Takachika/g" {} +
echo "Takafusa";find . -iname "*.yml" -exec sed -i -b "s/^ Takafusa/ #Takafusa/g" {} +
echo "Takahide";find . -iname "*.yml" -exec sed -i -b "s/^ Takahide/ #Takahide/g" {} +
echo "Takahisa";find . -iname "*.yml" -exec sed -i -b "s/^ Takahisa/ #Takahisa/g" {} +
echo "Takaie";find . -iname "*.yml" -exec sed -i -b "s/^ Takaie/ #Takaie/g" {} +
echo "Takakane";find . -iname "*.yml" -exec sed -i -b "s/^ Takakane/ #Takakane/g" {} +
echo "Takamichi";find . -iname "*.yml" -exec sed -i -b "s/^ Takamichi/ #Takamichi/g" {} +
echo "Takamitsu";find . -iname "*.yml" -exec sed -i -b "s/^ Takamitsu/ #Takamitsu/g" {} +
echo "Takamochi";find . -iname "*.yml" -exec sed -i -b "s/^ Takamochi/ #Takamochi/g" {} +
echo "Takamori";find . -iname "*.yml" -exec sed -i -b "s/^ Takamori/ #Takamori/g" {} +
echo "Takamoto";find . -iname "*.yml" -exec sed -i -b "s/^ Takamoto/ #Takamoto/g" {} +
echo "Takanaka";find . -iname "*.yml" -exec sed -i -b "s/^ Takanaka/ #Takanaka/g" {} +
echo "Takanao";find . -iname "*.yml" -exec sed -i -b "s/^ Takanao/ #Takanao/g" {} +
echo "Takanobu";find . -iname "*.yml" -exec sed -i -b "s/^ Takanobu/ #Takanobu/g" {} +
echo "Takasada";find . -iname "*.yml" -exec sed -i -b "s/^ Takasada/ #Takasada/g" {} +
echo "Takashige";find . -iname "*.yml" -exec sed -i -b "s/^ Takashige/ #Takashige/g" {} +
echo "Takasue";find . -iname "*.yml" -exec sed -i -b "s/^ Takasue/ #Takasue/g" {} +
echo "Takasuke";find . -iname "*.yml" -exec sed -i -b "s/^ Takasuke/ #Takasuke/g" {} +
echo "Takatsugu";find . -iname "*.yml" -exec sed -i -b "s/^ Takatsugu/ #Takatsugu/g" {} +
echo "Takayasu";find . -iname "*.yml" -exec sed -i -b "s/^ Takayasu/ #Takayasu/g" {} +
echo "Takayori";find . -iname "*.yml" -exec sed -i -b "s/^ Takayori/ #Takayori/g" {} +
echo "Takayoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Takayoshi/ #Takayoshi/g" {} +
echo "Takayuki";find . -iname "*.yml" -exec sed -i -b "s/^ Takayuki/ #Takayuki/g" {} +
echo "Takazane";find . -iname "*.yml" -exec sed -i -b "s/^ Takazane/ #Takazane/g" {} +
echo "Tamehiro";find . -iname "*.yml" -exec sed -i -b "s/^ Tamehiro/ #Tamehiro/g" {} +
echo "Tamekiyo";find . -iname "*.yml" -exec sed -i -b "s/^ Tamekiyo/ #Tamekiyo/g" {} +
echo "Tamenobu";find . -iname "*.yml" -exec sed -i -b "s/^ Tamenobu/ #Tamenobu/g" {} +
echo "Tameyori";find . -iname "*.yml" -exec sed -i -b "s/^ Tameyori/ #Tameyori/g" {} +
echo "Tamura";find . -iname "*.yml" -exec sed -i -b "s/^ Tamura/ #Tamura/g" {} +
echo "Tanehide";find . -iname "*.yml" -exec sed -i -b "s/^ Tanehide/ #Tanehide/g" {} +
echo "Tanemune";find . -iname "*.yml" -exec sed -i -b "s/^ Tanemune/ #Tanemune/g" {} +
echo "Tanenaga";find . -iname "*.yml" -exec sed -i -b "s/^ Tanenaga/ #Tanenaga/g" {} +
echo "Tanenao";find . -iname "*.yml" -exec sed -i -b "s/^ Tanenao/ #Tanenao/g" {} +
echo "Tanesada";find . -iname "*.yml" -exec sed -i -b "s/^ Tanesada/ #Tanesada/g" {} +
echo "Taneshige";find . -iname "*.yml" -exec sed -i -b "s/^ Taneshige/ #Taneshige/g" {} +
echo "Tanetsugu";find . -iname "*.yml" -exec sed -i -b "s/^ Tanetsugu/ #Tanetsugu/g" {} +
echo "Teruhiro";find . -iname "*.yml" -exec sed -i -b "s/^ Teruhiro/ #Teruhiro/g" {} +
echo "Tokishige";find . -iname "*.yml" -exec sed -i -b "s/^ Tokishige/ #Tokishige/g" {} +
echo "Tokitaka";find . -iname "*.yml" -exec sed -i -b "s/^ Tokitaka/ #Tokitaka/g" {} +
echo "Toku";find . -iname "*.yml" -exec sed -i -b "s/^ Toku/ #Toku/g" {} +
echo "Tome";find . -iname "*.yml" -exec sed -i -b "s/^ Tome/ #Tome/g" {} +
echo "Tomoe";find . -iname "*.yml" -exec sed -i -b "s/^ Tomoe/ #Tomoe/g" {} +
echo "Tomofusa";find . -iname "*.yml" -exec sed -i -b "s/^ Tomofusa/ #Tomofusa/g" {} +
echo "Tomohide";find . -iname "*.yml" -exec sed -i -b "s/^ Tomohide/ #Tomohide/g" {} +
echo "Tomohisa";find . -iname "*.yml" -exec sed -i -b "s/^ Tomohisa/ #Tomohisa/g" {} +
echo "Tomokane";find . -iname "*.yml" -exec sed -i -b "s/^ Tomokane/ #Tomokane/g" {} +
echo "Tomokata";find . -iname "*.yml" -exec sed -i -b "s/^ Tomokata/ #Tomokata/g" {} +
echo "Tomomasa";find . -iname "*.yml" -exec sed -i -b "s/^ Tomomasa/ #Tomomasa/g" {} +
echo "Tomomichi";find . -iname "*.yml" -exec sed -i -b "s/^ Tomomichi/ #Tomomichi/g" {} +
echo "Tomomori";find . -iname "*.yml" -exec sed -i -b "s/^ Tomomori/ #Tomomori/g" {} +
echo "Tomomune";find . -iname "*.yml" -exec sed -i -b "s/^ Tomomune/ #Tomomune/g" {} +
echo "Tomonao";find . -iname "*.yml" -exec sed -i -b "s/^ Tomonao/ #Tomonao/g" {} +
echo "Tomonari";find . -iname "*.yml" -exec sed -i -b "s/^ Tomonari/ #Tomonari/g" {} +
echo "Tomonobu";find . -iname "*.yml" -exec sed -i -b "s/^ Tomonobu/ #Tomonobu/g" {} +
echo "Tomonori";find . -iname "*.yml" -exec sed -i -b "s/^ Tomonori/ #Tomonori/g" {} +
echo "Tomosada";find . -iname "*.yml" -exec sed -i -b "s/^ Tomosada/ #Tomosada/g" {} +
echo "Tomotsune";find . -iname "*.yml" -exec sed -i -b "s/^ Tomotsune/ #Tomotsune/g" {} +
echo "Tomoyoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Tomoyoshi/ #Tomoyoshi/g" {} +
echo "Toshifusa";find . -iname "*.yml" -exec sed -i -b "s/^ Toshifusa/ #Toshifusa/g" {} +
echo "Toshikage";find . -iname "*.yml" -exec sed -i -b "s/^ Toshikage/ #Toshikage/g" {} +
echo "Toshikatsu";find . -iname "*.yml" -exec sed -i -b "s/^ Toshikatsu/ #Toshikatsu/g" {} +
echo "Toshimitsu";find . -iname "*.yml" -exec sed -i -b "s/^ Toshimitsu/ #Toshimitsu/g" {} +
echo "Toshimune";find . -iname "*.yml" -exec sed -i -b "s/^ Toshimune/ #Toshimune/g" {} +
echo "Toshinaga";find . -iname "*.yml" -exec sed -i -b "s/^ Toshinaga/ #Toshinaga/g" {} +
echo "Toshinao";find . -iname "*.yml" -exec sed -i -b "s/^ Toshinao/ #Toshinao/g" {} +
echo "Toshinobu";find . -iname "*.yml" -exec sed -i -b "s/^ Toshinobu/ #Toshinobu/g" {} +
echo "Toshitomo";find . -iname "*.yml" -exec sed -i -b "s/^ Toshitomo/ #Toshitomo/g" {} +
echo "Toyokuni";find . -iname "*.yml" -exec sed -i -b "s/^ Toyokuni/ #Toyokuni/g" {} +
echo "Tsugunari";find . -iname "*.yml" -exec sed -i -b "s/^ Tsugunari/ #Tsugunari/g" {} +
echo "Tsune";find . -iname "*.yml" -exec sed -i -b "s/^ Tsune/ #Tsune/g" {} +
echo "Tsuneaki";find . -iname "*.yml" -exec sed -i -b "s/^ Tsuneaki/ #Tsuneaki/g" {} +
echo "Tsunehide";find . -iname "*.yml" -exec sed -i -b "s/^ Tsunehide/ #Tsunehide/g" {} +
echo "Tsunehisa";find . -iname "*.yml" -exec sed -i -b "s/^ Tsunehisa/ #Tsunehisa/g" {} +
echo "Tsuneie";find . -iname "*.yml" -exec sed -i -b "s/^ Tsuneie/ #Tsuneie/g" {} +
echo "Tsunemitsu";find . -iname "*.yml" -exec sed -i -b "s/^ Tsunemitsu/ #Tsunemitsu/g" {} +
echo "Tsunenaga";find . -iname "*.yml" -exec sed -i -b "s/^ Tsunenaga/ #Tsunenaga/g" {} +
echo "Tsunetada";find . -iname "*.yml" -exec sed -i -b "s/^ Tsunetada/ #Tsunetada/g" {} +
echo "Tsuneyasu";find . -iname "*.yml" -exec sed -i -b "s/^ Tsuneyasu/ #Tsuneyasu/g" {} +
echo "Tsuneyoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Tsuneyoshi/ #Tsuneyoshi/g" {} +
echo "Ujihira";find . -iname "*.yml" -exec sed -i -b "s/^ Ujihira/ #Ujihira/g" {} +
echo "Ujikage";find . -iname "*.yml" -exec sed -i -b "s/^ Ujikage/ #Ujikage/g" {} +
echo "Ujikatsu";find . -iname "*.yml" -exec sed -i -b "s/^ Ujikatsu/ #Ujikatsu/g" {} +
echo "Ujinaga";find . -iname "*.yml" -exec sed -i -b "s/^ Ujinaga/ #Ujinaga/g" {} +
echo "Ujinari";find . -iname "*.yml" -exec sed -i -b "s/^ Ujinari/ #Ujinari/g" {} +
echo "Ujinori";find . -iname "*.yml" -exec sed -i -b "s/^ Ujinori/ #Ujinori/g" {} +
echo "Ujisuke";find . -iname "*.yml" -exec sed -i -b "s/^ Ujisuke/ #Ujisuke/g" {} +
echo "Ushi";find . -iname "*.yml" -exec sed -i -b "s/^ Ushi/ #Ushi/g" {} +
echo "Yasha";find . -iname "*.yml" -exec sed -i -b "s/^ Yasha/ #Yasha/g" {} +
echo "Yasu";find . -iname "*.yml" -exec sed -i -b "s/^ Yasu/ #Yasu/g" {} +
echo "Yasuharu";find . -iname "*.yml" -exec sed -i -b "s/^ Yasuharu/ #Yasuharu/g" {} +
echo "Yasuhide";find . -iname "*.yml" -exec sed -i -b "s/^ Yasuhide/ #Yasuhide/g" {} +
echo "Yasukage";find . -iname "*.yml" -exec sed -i -b "s/^ Yasukage/ #Yasukage/g" {} +
echo "Yasumasa";find . -iname "*.yml" -exec sed -i -b "s/^ Yasumasa/ #Yasumasa/g" {} +
echo "Yasumori";find . -iname "*.yml" -exec sed -i -b "s/^ Yasumori/ #Yasumori/g" {} +
echo "Yasunaga";find . -iname "*.yml" -exec sed -i -b "s/^ Yasunaga/ #Yasunaga/g" {} +
echo "Yasunari";find . -iname "*.yml" -exec sed -i -b "s/^ Yasunari/ #Yasunari/g" {} +
echo "Yasunobu";find . -iname "*.yml" -exec sed -i -b "s/^ Yasunobu/ #Yasunobu/g" {} +
echo "Yasunori";find . -iname "*.yml" -exec sed -i -b "s/^ Yasunori/ #Yasunori/g" {} +
echo "Yasusue";find . -iname "*.yml" -exec sed -i -b "s/^ Yasusue/ #Yasusue/g" {} +
echo "Yasusuke";find . -iname "*.yml" -exec sed -i -b "s/^ Yasusuke/ #Yasusuke/g" {} +
echo "Yasutada";find . -iname "*.yml" -exec sed -i -b "s/^ Yasutada/ #Yasutada/g" {} +
echo "Yasutomo";find . -iname "*.yml" -exec sed -i -b "s/^ Yasutomo/ #Yasutomo/g" {} +
echo "Yasutoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Yasutoshi/ #Yasutoshi/g" {} +
echo "Yasuyoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Yasuyoshi/ #Yasuyoshi/g" {} +
echo "Yasuzane";find . -iname "*.yml" -exec sed -i -b "s/^ Yasuzane/ #Yasuzane/g" {} +
echo "Yoriaki";find . -iname "*.yml" -exec sed -i -b "s/^ Yoriaki/ #Yoriaki/g" {} +
echo "Yorichika";find . -iname "*.yml" -exec sed -i -b "s/^ Yorichika/ #Yorichika/g" {} +
echo "Yorifusa";find . -iname "*.yml" -exec sed -i -b "s/^ Yorifusa/ #Yorifusa/g" {} +
echo "Yoriharu";find . -iname "*.yml" -exec sed -i -b "s/^ Yoriharu/ #Yoriharu/g" {} +
echo "Yorihira";find . -iname "*.yml" -exec sed -i -b "s/^ Yorihira/ #Yorihira/g" {} +
echo "Yorimori";find . -iname "*.yml" -exec sed -i -b "s/^ Yorimori/ #Yorimori/g" {} +
echo "Yorioki";find . -iname "*.yml" -exec sed -i -b "s/^ Yorioki/ #Yorioki/g" {} +
echo "Yorishige";find . -iname "*.yml" -exec sed -i -b "s/^ Yorishige/ #Yorishige/g" {} +
echo "Yoritada";find . -iname "*.yml" -exec sed -i -b "s/^ Yoritada/ #Yoritada/g" {} +
echo "Yoritaka";find . -iname "*.yml" -exec sed -i -b "s/^ Yoritaka/ #Yoritaka/g" {} +
echo "Yoritoki";find . -iname "*.yml" -exec sed -i -b "s/^ Yoritoki/ #Yoritoki/g" {} +
echo "Yoritsugu";find . -iname "*.yml" -exec sed -i -b "s/^ Yoritsugu/ #Yoritsugu/g" {} +
echo "Yoritsuna";find . -iname "*.yml" -exec sed -i -b "s/^ Yoritsuna/ #Yoritsuna/g" {} +
echo "Yoriuji";find . -iname "*.yml" -exec sed -i -b "s/^ Yoriuji/ #Yoriuji/g" {} +
echo "Yoriyasu";find . -iname "*.yml" -exec sed -i -b "s/^ Yoriyasu/ #Yoriyasu/g" {} +
echo "Yoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshi/ #Yoshi/g" {} +
echo "Yoshiaki";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshiaki/ #Yoshiaki/g" {} +
echo "Yoshiakira";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshiakira/ #Yoshiakira/g" {} +
echo "Yoshiari";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshiari/ #Yoshiari/g" {} +
echo "Yoshichika";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshichika/ #Yoshichika/g" {} +
echo "Yoshiharu";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshiharu/ #Yoshiharu/g" {} +
echo "Yoshihide";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshihide/ #Yoshihide/g" {} +
echo "Yoshihira";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshihira/ #Yoshihira/g" {} +
echo "Yoshihiro";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshihiro/ #Yoshihiro/g" {} +
echo "Yoshihisa";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshihisa/ #Yoshihisa/g" {} +
echo "Yoshihito";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshihito/ #Yoshihito/g" {} +
echo "Yoshikado";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshikado/ #Yoshikado/g" {} +
echo "Yoshikage";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshikage/ #Yoshikage/g" {} +
echo "Yoshikane";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshikane/ #Yoshikane/g" {} +
echo "Yoshikata";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshikata/ #Yoshikata/g" {} +
echo "Yoshikatsu";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshikatsu/ #Yoshikatsu/g" {} +
echo "Yoshikiyo";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshikiyo/ #Yoshikiyo/g" {} +
echo "Yoshikuni";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshikuni/ #Yoshikuni/g" {} +
echo "Yoshimasa";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshimasa/ #Yoshimasa/g" {} +
echo "Yoshimichi";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshimichi/ #Yoshimichi/g" {} +
echo "Yoshimitsu";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshimitsu/ #Yoshimitsu/g" {} +
echo "Yoshimochi";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshimochi/ #Yoshimochi/g" {} +
echo "Yoshimori";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshimori/ #Yoshimori/g" {} +
echo "Yoshimoto";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshimoto/ #Yoshimoto/g" {} +
echo "Yoshimune";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshimune/ #Yoshimune/g" {} +
echo "Yoshimura";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshimura/ #Yoshimura/g" {} +
echo "Yoshinaga";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshinaga/ #Yoshinaga/g" {} +
echo "Yoshinao";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshinao/ #Yoshinao/g" {} +
echo "Yoshinari";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshinari/ #Yoshinari/g" {} +
echo "Yoshinobu";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshinobu/ #Yoshinobu/g" {} +
echo "Yoshinori";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshinori/ #Yoshinori/g" {} +
echo "Yoshioki";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshioki/ #Yoshioki/g" {} +
echo "Yoshisada";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshisada/ #Yoshisada/g" {} +
echo "Yoshisato";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshisato/ #Yoshisato/g" {} +
echo "Yoshishige";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshishige/ #Yoshishige/g" {} +
echo "Yoshisuke";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshisuke/ #Yoshisuke/g" {} +
echo "Yoshitada";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshitada/ #Yoshitada/g" {} +
echo "Yoshitaka";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshitaka/ #Yoshitaka/g" {} +
echo "Yoshitane";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshitane/ #Yoshitane/g" {} +
echo "Yoshitoki";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshitoki/ #Yoshitoki/g" {} +
echo "Yoshitomo";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshitomo/ #Yoshitomo/g" {} +
echo "Yoshitoshi";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshitoshi/ #Yoshitoshi/g" {} +
echo "Yoshitsugu";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshitsugu/ #Yoshitsugu/g" {} +
echo "Yoshitsuna";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshitsuna/ #Yoshitsuna/g" {} +
echo "Yoshiuji";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshiuji/ #Yoshiuji/g" {} +
echo "Yoshiyasu";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshiyasu/ #Yoshiyasu/g" {} +
echo "Yoshiyori";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshiyori/ #Yoshiyori/g" {} +
echo "Yoshiyuki";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshiyuki/ #Yoshiyuki/g" {} +
echo "Yoshizane";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshizane/ #Yoshizane/g" {} +
echo "Yoshizumi";find . -iname "*.yml" -exec sed -i -b "s/^ Yoshizumi/ #Yoshizumi/g" {} +
echo "Yukihiro";find . -iname "*.yml" -exec sed -i -b "s/^ Yukihiro/ #Yukihiro/g" {} +
echo "Yukimasa";find . -iname "*.yml" -exec sed -i -b "s/^ Yukimasa/ #Yukimasa/g" {} +
echo "Yukimori";find . -iname "*.yml" -exec sed -i -b "s/^ Yukimori/ #Yukimori/g" {} +
echo "Yukimura";find . -iname "*.yml" -exec sed -i -b "s/^ Yukimura/ #Yukimura/g" {} +
echo "Yukinaga";find . -iname "*.yml" -exec sed -i -b "s/^ Yukinaga/ #Yukinaga/g" {} +
echo "Yukishige";find . -iname "*.yml" -exec sed -i -b "s/^ Yukishige/ #Yukishige/g" {} +
echo "Furi";find . -iname "*.yml" -exec sed -i -b "s/^ Furi/ #Furi/g" {} +
echo "Tama";find . -iname "*.yml" -exec sed -i -b "s/^ Tama/ #Tama/g" {} +
echo "Umituku";find . -iname "*.yml" -exec sed -i -b "s/^ Umituku/ #Umituku/g" {} +
echo "Yuvaraj";find . -iname "*.yml" -exec sed -i -b "s/^ Yuvaraj/ #Yuvaraj/g" {} +
echo "Bian";find . -iname "*.yml" -exec sed -i -b "s/^ Bian/ #Bian/g" {} +
echo "Ishanavarman";find . -iname "*.yml" -exec sed -i -b "s/^ Ishanavarman/ #Ishanavarman/g" {} +
echo "Lugo";find . -iname "*.yml" -exec sed -i -b "s/^ Lugo/ #Lugo/g" {} +
echo "Puti";find . -iname "*.yml" -exec sed -i -b "s/^ Puti/ #Puti/g" {} +
echo "Bato";find . -iname "*.yml" -exec sed -i -b "s/^ Bato/ #Bato/g" {} +
echo "Huna";find . -iname "*.yml" -exec sed -i -b "s/^ Huna/ #Huna/g" {} +
echo "Lilo";find . -iname "*.yml" -exec sed -i -b "s/^ Lilo/ #Lilo/g" {} +
echo "Uto";find . -iname "*.yml" -exec sed -i -b "s/^ Uto/ #Uto/g" {} +
echo "Sat";find . -iname "*.yml" -exec sed -i -b "s/^ Sat/ #Sat/g" {} +
echo "Devasena";find . -iname "*.yml" -exec sed -i -b "s/^ Devasena/ #Devasena/g" {} +
echo "Prabhakara";find . -iname "*.yml" -exec sed -i -b "s/^ Prabhakara/ #Prabhakara/g" {} +
echo "Loka";find . -iname "*.yml" -exec sed -i -b "s/^ Loka/ #Loka/g" {} +
echo "Keti";find . -iname "*.yml" -exec sed -i -b "s/^ Keti/ #Keti/g" {} +
echo "Biala";find . -iname "*.yml" -exec sed -i -b "s/^ Biala/ #Biala/g" {} +
echo "Dori";find . -iname "*.yml" -exec sed -i -b "s/^ Dori/ #Dori/g" {} +
echo "Achariya";find . -iname "*.yml" -exec sed -i -b "s/^ Achariya/ #Achariya/g" {} +
echo "Anchali";find . -iname "*.yml" -exec sed -i -b "s/^ Anchali/ #Anchali/g" {} +
echo "Anh";find . -iname "*.yml" -exec sed -i -b "s/^ Anh/ #Anh/g" {} +
echo "Awan";find . -iname "*.yml" -exec sed -i -b "s/^ Awan/ #Awan/g" {} +
echo "Ban";find . -iname "*.yml" -exec sed -i -b "s/^ Ban/ #Ban/g" {} +
echo "Bien";find . -iname "*.yml" -exec sed -i -b "s/^ Bien/ #Bien/g" {} +
echo "Binh";find . -iname "*.yml" -exec sed -i -b "s/^ Binh/ #Binh/g" {} +
echo "Bua";find . -iname "*.yml" -exec sed -i -b "s/^ Bua/ #Bua/g" {} +
echo "Canh";find . -iname "*.yml" -exec sed -i -b "s/^ Canh/ #Canh/g" {} +
echo "Chau";find . -iname "*.yml" -exec sed -i -b "s/^ Chau/ #Chau/g" {} +
echo "Chi";find . -iname "*.yml" -exec sed -i -b "s/^ Chi/ #Chi/g" {} +
echo "Chieu";find . -iname "*.yml" -exec sed -i -b "s/^ Chieu/ #Chieu/g" {} +
echo "Chung";find . -iname "*.yml" -exec sed -i -b "s/^ Chung/ #Chung/g" {} +
echo "Chuong";find . -iname "*.yml" -exec sed -i -b "s/^ Chuong/ #Chuong/g" {} +
echo "Diem";find . -iname "*.yml" -exec sed -i -b "s/^ Diem/ #Diem/g" {} +
echo "Dien";find . -iname "*.yml" -exec sed -i -b "s/^ Dien/ #Dien/g" {} +
echo "Diep";find . -iname "*.yml" -exec sed -i -b "s/^ Diep/ #Diep/g" {} +
echo "Dinh";find . -iname "*.yml" -exec sed -i -b "s/^ Dinh/ #Dinh/g" {} +
echo "Duc";find . -iname "*.yml" -exec sed -i -b "s/^ Duc/ #Duc/g" {} +
echo "Duong";find . -iname "*.yml" -exec sed -i -b "s/^ Duong/ #Duong/g" {} +
echo "Emon";find . -iname "*.yml" -exec sed -i -b "s/^ Emon/ #Emon/g" {} +
echo "Giang";find . -iname "*.yml" -exec sed -i -b "s/^ Giang/ #Giang/g" {} +
echo "Hai";find . -iname "*.yml" -exec sed -i -b "s/^ Hai/ #Hai/g" {} +
echo "Hanh";find . -iname "*.yml" -exec sed -i -b "s/^ Hanh/ #Hanh/g" {} +
echo "Hien";find . -iname "*.yml" -exec sed -i -b "s/^ Hien/ #Hien/g" {} +
echo "Hieu";find . -iname "*.yml" -exec sed -i -b "s/^ Hieu/ #Hieu/g" {} +
echo "Hoa";find . -iname "*.yml" -exec sed -i -b "s/^ Hoa/ #Hoa/g" {} +
echo "Hoai";find . -iname "*.yml" -exec sed -i -b "s/^ Hoai/ #Hoai/g" {} +
echo "Hoang";find . -iname "*.yml" -exec sed -i -b "s/^ Hoang/ #Hoang/g" {} +
echo "Hop";find . -iname "*.yml" -exec sed -i -b "s/^ Hop/ #Hop/g" {} +
echo "Hue";find . -iname "*.yml" -exec sed -i -b "s/^ Hue/ #Hue/g" {} +
echo "Hung";find . -iname "*.yml" -exec sed -i -b "s/^ Hung/ #Hung/g" {} +
echo "Huong";find . -iname "*.yml" -exec sed -i -b "s/^ Huong/ #Huong/g" {} +
echo "Huy";find . -iname "*.yml" -exec sed -i -b "s/^ Huy/ #Huy/g" {} +
echo "Huyen";find . -iname "*.yml" -exec sed -i -b "s/^ Huyen/ #Huyen/g" {} +
echo "Khanh";find . -iname "*.yml" -exec sed -i -b "s/^ Khanh/ #Khanh/g" {} +
echo "Khoa";find . -iname "*.yml" -exec sed -i -b "s/^ Khoa/ #Khoa/g" {} +
echo "Khoi";find . -iname "*.yml" -exec sed -i -b "s/^ Khoi/ #Khoi/g" {} +
echo "Khue";find . -iname "*.yml" -exec sed -i -b "s/^ Khue/ #Khue/g" {} +
echo "Khuyen";find . -iname "*.yml" -exec sed -i -b "s/^ Khuyen/ #Khuyen/g" {} +
echo "Kien";find . -iname "*.yml" -exec sed -i -b "s/^ Kien/ #Kien/g" {} +
echo "Kieu";find . -iname "*.yml" -exec sed -i -b "s/^ Kieu/ #Kieu/g" {} +
echo "Kim";find . -iname "*.yml" -exec sed -i -b "s/^ Kim/ #Kim/g" {} +
echo "Kinh";find . -iname "*.yml" -exec sed -i -b "s/^ Kinh/ #Kinh/g" {} +
echo "Le";find . -iname "*.yml" -exec sed -i -b "s/^ Le/ #Le/g" {} +
echo "Liem";find . -iname "*.yml" -exec sed -i -b "s/^ Liem/ #Liem/g" {} +
echo "Lien";find . -iname "*.yml" -exec sed -i -b "s/^ Lien/ #Lien/g" {} +
echo "Linh";find . -iname "*.yml" -exec sed -i -b "s/^ Linh/ #Linh/g" {} +
echo "Loan";find . -iname "*.yml" -exec sed -i -b "s/^ Loan/ #Loan/g" {} +
echo "Loc";find . -iname "*.yml" -exec sed -i -b "s/^ Loc/ #Loc/g" {} +
echo "Ly";find . -iname "*.yml" -exec sed -i -b "s/^ Ly/ #Ly/g" {} +
echo "Manh";find . -iname "*.yml" -exec sed -i -b "s/^ Manh/ #Manh/g" {} +
echo "Minh";find . -iname "*.yml" -exec sed -i -b "s/^ Minh/ #Minh/g" {} +
echo "My";find . -iname "*.yml" -exec sed -i -b "s/^ My/ #My/g" {} +
echo "Ngan";find . -iname "*.yml" -exec sed -i -b "s/^ Ngan/ #Ngan/g" {} +
echo "Nhung";find . -iname "*.yml" -exec sed -i -b "s/^ Nhung/ #Nhung/g" {} +
echo "Phong";find . -iname "*.yml" -exec sed -i -b "s/^ Phong/ #Phong/g" {} +
echo "Phu";find . -iname "*.yml" -exec sed -i -b "s/^ Phu/ #Phu/g" {} +
echo "Phuc";find . -iname "*.yml" -exec sed -i -b "s/^ Phuc/ #Phuc/g" {} +
echo "Phuong";find . -iname "*.yml" -exec sed -i -b "s/^ Phuong/ #Phuong/g" {} +
echo "Quang";find . -iname "*.yml" -exec sed -i -b "s/^ Quang/ #Quang/g" {} +
echo "Son";find . -iname "*.yml" -exec sed -i -b "s/^ Son/ #Son/g" {} +
echo "Sri";find . -iname "*.yml" -exec sed -i -b "s/^ Sri/ #Sri/g" {} +
echo "Thanh";find . -iname "*.yml" -exec sed -i -b "s/^ Thanh/ #Thanh/g" {} +
echo "Thao";find . -iname "*.yml" -exec sed -i -b "s/^ Thao/ #Thao/g" {} +
echo "Thi";find . -iname "*.yml" -exec sed -i -b "s/^ Thi/ #Thi/g" {} +
echo "Thien";find . -iname "*.yml" -exec sed -i -b "s/^ Thien/ #Thien/g" {} +
echo "Thom";find . -iname "*.yml" -exec sed -i -b "s/^ Thom/ #Thom/g" {} +
echo "Thu";find . -iname "*.yml" -exec sed -i -b "s/^ Thu/ #Thu/g" {} +
echo "Thuan";find . -iname "*.yml" -exec sed -i -b "s/^ Thuan/ #Thuan/g" {} +
echo "Thuong";find . -iname "*.yml" -exec sed -i -b "s/^ Thuong/ #Thuong/g" {} +
echo "Thuy";find . -iname "*.yml" -exec sed -i -b "s/^ Thuy/ #Thuy/g" {} +
echo "Thuyet";find . -iname "*.yml" -exec sed -i -b "s/^ Thuyet/ #Thuyet/g" {} +
echo "Tien";find . -iname "*.yml" -exec sed -i -b "s/^ Tien/ #Tien/g" {} +
echo "Toan";find . -iname "*.yml" -exec sed -i -b "s/^ Toan/ #Toan/g" {} +
echo "Trai";find . -iname "*.yml" -exec sed -i -b "s/^ Trai/ #Trai/g" {} +
echo "Trang";find . -iname "*.yml" -exec sed -i -b "s/^ Trang/ #Trang/g" {} +
echo "Tri";find . -iname "*.yml" -exec sed -i -b "s/^ Tri/ #Tri/g" {} +
echo "Trinh";find . -iname "*.yml" -exec sed -i -b "s/^ Trinh/ #Trinh/g" {} +
echo "Trung";find . -iname "*.yml" -exec sed -i -b "s/^ Trung/ #Trung/g" {} +
echo "Tuyen";find . -iname "*.yml" -exec sed -i -b "s/^ Tuyen/ #Tuyen/g" {} +
echo "Usa";find . -iname "*.yml" -exec sed -i -b "s/^ Usa/ #Usa/g" {} +
echo "Quynh";find . -iname "*.yml" -exec sed -i -b "s/^ Quynh/ #Quynh/g" {} +
echo "Tuyet";find . -iname "*.yml" -exec sed -i -b "s/^ Tuyet/ #Tuyet/g" {} +
echo "Amo";find . -iname "*.yml" -exec sed -i -b "s/^ Amo/ #Amo/g" {} +
echo "Basilissa";find . -iname "*.yml" -exec sed -i -b "s/^ Basilissa/ #Basilissa/g" {} +
echo "Claritta";find . -iname "*.yml" -exec sed -i -b "s/^ Claritta/ #Claritta/g" {} +
echo "Flurinda";find . -iname "*.yml" -exec sed -i -b "s/^ Flurinda/ #Flurinda/g" {} +
echo "Gionina";find . -iname "*.yml" -exec sed -i -b "s/^ Gionina/ #Gionina/g" {} +
echo "Salvia";find . -iname "*.yml" -exec sed -i -b "s/^ Salvia/ #Salvia/g" {} +
echo "Seraina";find . -iname "*.yml" -exec sed -i -b "s/^ Seraina/ #Seraina/g" {} +
echo "Ursina";find . -iname "*.yml" -exec sed -i -b "s/^ Ursina/ #Ursina/g" {} +
echo "Baltran";find . -iname "*.yml" -exec sed -i -b "s/^ Baltran/ #Baltran/g" {} +
echo "Camil";find . -iname "*.yml" -exec sed -i -b "s/^ Camil/ #Camil/g" {} +
echo "Flurin";find . -iname "*.yml" -exec sed -i -b "s/^ Flurin/ #Flurin/g" {} +
echo "Frideric";find . -iname "*.yml" -exec sed -i -b "s/^ Frideric/ #Frideric/g" {} +
echo "Fridolin";find . -iname "*.yml" -exec sed -i -b "s/^ Fridolin/ #Fridolin/g" {} +
echo "Gion";find . -iname "*.yml" -exec sed -i -b "s/^ Gion/ #Gion/g" {} +
echo "Ildefons";find . -iname "*.yml" -exec sed -i -b "s/^ Ildefons/ #Ildefons/g" {} +
echo "Leodegar";find . -iname "*.yml" -exec sed -i -b "s/^ Leodegar/ #Leodegar/g" {} +
echo "Linard";find . -iname "*.yml" -exec sed -i -b "s/^ Linard/ #Linard/g" {} +
echo "Tgasper";find . -iname "*.yml" -exec sed -i -b "s/^ Tgasper/ #Tgasper/g" {} +
echo "Ursicin";find . -iname "*.yml" -exec sed -i -b "s/^ Ursicin/ #Ursicin/g" {} +
echo "Jojin";find . -iname "*.yml" -exec sed -i -b "s/^ Jojin/ #Jojin/g" {} +
echo "Lo";find . -iname "*.yml" -exec sed -i -b "s/^ Lo/ #Lo/g" {} +
echo "Boc";find . -iname "*.yml" -exec sed -i -b "s/^ Boc/ #Boc/g" {} +
echo "Ayal";find . -iname "*.yml" -exec sed -i -b "s/^ Ayal/ #Ayal/g" {} +
echo "Pi";find . -iname "*.yml" -exec sed -i -b "s/^ Pi/ #Pi/g" {} +
echo "Shougui";find . -iname "*.yml" -exec sed -i -b "s/^ Shougui/ #Shougui/g" {} +

