name: Check Localization File Endings
on: [push]
jobs:
  check_localization_file_endings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          submodules: recursive
      - name: "Run Script"
        run: |
          python3 CK3_Validator/test_scripts/check_localization_file_endings.py "BP"
